/*********************************************************************
*                                                                    *
*                SEGGER Microcontroller GmbH & Co. KG                *
*        Solutions for real time microcontroller applications        *
*                                                                    *
**********************************************************************
*                                                                    *
* C-file generated by:                                               *
*                                                                    *
*        GUI_Builder for emWin version 5.32                          *
*        Compiled Oct  8 2015, 11:59:02                              *
*        (c) 2015 Segger Microcontroller GmbH & Co. KG               *
*                                                                    *
**********************************************************************
*                                                                    *
*        Internet: www.segger.com  Support: support@segger.com       *
*                                                                    *
**********************************************************************
*/

// USER START (Optionally insert additional includes)
// USER END

#include "DIALOG.h"
/*********************************************************************
*
*       Defines
*
**********************************************************************
*/
#define ID_WINDOW_0 (GUI_ID_USER + 0x00)
#define ID_BUTTON_0 (GUI_ID_USER + 0x02)
#define ID_BUTTON_1 (GUI_ID_USER + 0x03)
#define DATE_DIS (WM_USER+1)
// USER START (Optionally insert additional defines)
// USER END

/*********************************************************************
*
*       Static data
*
**********************************************************************
*/

// USER START (Optionally insert additional static data)
// USER END

/*********************************************************************
*
*       _aDialogCreate
*/
static const GUI_WIDGET_CREATE_INFO _aDialogCreate[] = {
  { WINDOW_CreateIndirect, "Window", ID_WINDOW_0, 0, 0, 480, 320, 0, 0x0, 0 },
  { BUTTON_CreateIndirect, "EXIT", ID_BUTTON_0, 350, 50, 80, 40, 0, 0x0, 0 },
  { BUTTON_CreateIndirect, "OK", ID_BUTTON_1, 350, 100, 80, 40, 0, 0x0, 0 }
  // USER START (Optionally insert additional widgets)
  // USER END
};

/*********************************************************************
*
*       Static code
*
**********************************************************************
*/

// USER START (Optionally insert additional static code)
// USER END
extern WM_HWIN CreateWin1(void);
extern WM_HWIN SettingWindow(void);
CALENDAR_DATE Date;

	int Hour;
	int Min;
	int Sec;

/*********************************************************************
*
*       _cbDialog
*/
extern WM_HWIN            hWinBk;
extern int show_Flag;
static void _cbDialog(WM_MESSAGE * pMsg) {
  WM_HWIN hItem;
  int     NCode;
  int     Id;
  static WM_HWIN hCalen;
	GUI_HMEM H_QR;
  static int d1;
  static int d2;
  static int d3;
  // USER START (Optionally insert additional variables)
  // USER END

  switch (pMsg->MsgId) {
  case WM_PAINT:
		GUI_DrawGradientV(0,0,479,319,GUI_LIGHTBLUE,GUI_BLUE);
	
	  GUI_SetTextMode(GUI_TM_TRANS);
	  GUI_SetColor(GUI_BLACK);
	  GUI_SetFont(&GUI_Font20B_1);	
	  GUI_DispDecAt(d1,615,300,2);
	  GUI_DispDecAt(d2, 665, 300, 2);
	  GUI_DispDecAt(d3, 715, 300, 2);
	  GUI_DispStringAt(":", 640, 300);
	  GUI_DispStringAt(":", 690, 300);
	
	H_QR = GUI_QR_Create("http://www.baidu.com",3,GUI_QR_ECLEVEL_M,0);
	GUI_QR_Draw(H_QR,320,200);
	  break;
  case WM_INIT_DIALOG:
    //
    // Initialization of 'Listwheel'
    //

	CALENDAR_SetDefaultFont(CALENDAR_FI_CONTENT,&GUI_Font20B_1);
	CALENDAR_SetDefaultFont(CALENDAR_FI_HEADER, &GUI_Font20_1);

	CALENDAR_SetDefaultSize(CALENDAR_SI_HEADER,30);
	CALENDAR_SetDefaultSize(CALENDAR_SI_CELL_X,40);
	CALENDAR_SetDefaultSize(CALENDAR_SI_CELL_Y,25);

	hCalen = CALENDAR_Create(pMsg->hWin,20,20,2019,4,10,2,0,0);
    // USER START (Optionally insert additional code for further widget initialization)
    // USER END
    break;
  case WM_NOTIFY_PARENT:
    Id    = WM_GetId(pMsg->hWinSrc);
    NCode = pMsg->Data.v;
    switch(Id) {
    case ID_BUTTON_0: // Notifications sent by 'return'
      switch(NCode) {
      case WM_NOTIFICATION_CLICKED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      case WM_NOTIFICATION_RELEASED:
        // USER START (Optionally insert code for reacting on notification message)
			
		  WM_DeleteWindow(pMsg->hWin);
		  SettingWindow();
		
        // USER END
        break;
      // USER START (Optionally insert additional code for further notification handling)
      // USER END
      }
      break;
    case ID_BUTTON_1: // Notifications sent by 'OK'
      switch(NCode) {
      case WM_NOTIFICATION_CLICKED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      case WM_NOTIFICATION_RELEASED:
        // USER START (Optionally insert code for reacting on notification message)
		  // hCalen
		  CALENDAR_GetSel(hCalen, &Date);
		  CALENDAR_SetDate(hCalen, &Date);

		 // WM_SendMessageNoPara(WIN_Header, DATE_DIS);
		  WM_InvalidateWindow(pMsg->hWin);
        // USER END
        break;
      // USER START (Optionally insert additional code for further notification handling)
      // USER END
      }
      break;
    // USER START (Optionally insert additional code for further Ids)
    // USER END
	
    }
    break;
  // USER START (Optionally insert additional message handling)
  // USER END
  default:
    WM_DefaultProc(pMsg);
    break;
  }
}

/*********************************************************************
*
*       Public code
*
**********************************************************************
*/
/*********************************************************************
*
*       CreateWindow
*/
WM_HWIN CalenderWindow(void);
WM_HWIN CalenderWindow(void) {
  WM_HWIN hWin;

  hWin = GUI_CreateDialogBox(_aDialogCreate, GUI_COUNTOF(_aDialogCreate), _cbDialog, WM_HBKWIN, 0, 0);
  return hWin;
}

// USER START (Optionally insert additional public code)
// USER END

/*************************** End of file ****************************/
