/*********************************************************************
*                                                                    *
*                SEGGER Microcontroller GmbH & Co. KG                *
*        Solutions for real time microcontroller applications        *
*                                                                    *
**********************************************************************
*                                                                    *
* C-file generated by:                                               *
*                                                                    *
*        GUI_Builder for emWin version 5.22                          *
*        Compiled Jul  4 2013, 15:16:01                              *
*        (c) 2013 Segger Microcontroller GmbH & Co. KG               *
*                                                                    *
**********************************************************************
*                                                                    *
*        Internet: www.segger.com  Support: support@segger.com       *
*                                                                    *
**********************************************************************
*/

// USER START (Optionally insert additional includes)
// USER END

#include "DIALOG.h"
#include "stm32f4xx_hal.h"
#include "rtc.h"
#include "str.h"
/*********************************************************************
*
*       Defines
*
**********************************************************************
*/
#define ID_WINDOW_0 (GUI_ID_USER + 0x00)


// USER START (Optionally insert additional defines)
// USER END

/*********************************************************************
*
*       Static data
*
**********************************************************************
*/

// USER START (Optionally insert additional static data)
// USER END

/*********************************************************************
*
*       _aDialogCreate
*/
static const GUI_WIDGET_CREATE_INFO _aDialogCreate[] = {
  { WINDOW_CreateIndirect, "Window", ID_WINDOW_0, 0, 0, 480, 30, 0, 0x0, 0 },
  // USER START (Optionally insert additional widgets)
  // USER END
};

/*********************************************************************
*
*       Static code
*
**********************************************************************
*/

// USER START (Optionally insert additional static code)
// USER END

/*********************************************************************
*
*       _cbDialog
*/
char str_time[15];

	RTC_TimeTypeDef RTC_Time;
	RTC_DateTypeDef RTC_Date;

static void _cbDialog(WM_MESSAGE * pMsg) {

	GUI_RECT Rect;

  // USER START (Optionally insert additional variables)
  // USER END

  switch (pMsg->MsgId) {
  // USER START (Optionally insert additional message handling)
		case WM_TIMER:

			HAL_RTC_GetTime(&hrtc,&RTC_Time,RTC_FORMAT_BIN);			
			HAL_RTC_GetDate(&hrtc,&RTC_Date,RTC_FORMAT_BIN);
	
			WM_RestartTimer(pMsg->Data.v,1000);
			
			Rect.x0 = 400;
			Rect.x1 = 480;
			Rect.y0 = 0;
			Rect.y1 = 30;

			WM_InvalidateArea(&Rect);
		//WM_InvalidateWindow(pMsg->hWin);
			break;
		case WM_PAINT:
			GUI_DrawGradientV(0,0,479,15,GUI_LIGHTBLUE,0x00FF3030);
			GUI_DrawGradientV(0,15,479,30,0x00FF3030,GUI_LIGHTBLUE);
	
			GUI_SetTextMode(GUI_TM_TRANS);
			GUI_SetFont(GUI_FONT_20B_1);
			GUI_SetColor(GUI_BLACK);
			GUI_DispStringHCenterAt("Bubble Lab",240,5);
		
			GUI_SetFont(GUI_FONT_13B_1);
		if (Set.visable)
		{
			sprintf(str_time,"%2d:%2d:%2d",RTC_Time.Hours,RTC_Time.Minutes,RTC_Time.Seconds);
			GUI_DispStringHCenterAt(str_time,440,2);	
			sprintf(str_time,"20%02d/%d/%d",RTC_Date.Year,RTC_Date.Month,RTC_Date.Date);
			GUI_DispStringHCenterAt(str_time,440,17);
		}

		break;
  // USER END
  default:
    WM_DefaultProc(pMsg);
    break;
  }
}

/*********************************************************************
*
*       Public code
*
**********************************************************************
*/
/*********************************************************************
*
*       CreateWindow
*/
WM_HWIN HeadWindow(void);
WM_HWIN HeadWindow(void) {
  WM_HWIN hWin;
	WM_HTIMER h_timer;
  hWin = GUI_CreateDialogBox(_aDialogCreate, GUI_COUNTOF(_aDialogCreate), _cbDialog, WM_HBKWIN, 0, 0);
	h_timer = WM_CreateTimer(hWin,0,1000,0);
  return hWin;
}

// USER START (Optionally insert additional public code)
// USER END

/*************************** End of file ****************************/
