/*********************************************************************
*                                                                    *
*                SEGGER Microcontroller GmbH & Co. KG                *
*        Solutions for real time microcontroller applications        *
*                                                                    *
**********************************************************************
*                                                                    *
* C-file generated by:                                               *
*                                                                    *
*        GUI_Builder for emWin version 5.22                          *
*        Compiled Jul  4 2013, 15:16:01                              *
*        (c) 2013 Segger Microcontroller GmbH & Co. KG               *
*                                                                    *
**********************************************************************
*                                                                    *
*        Internet: www.segger.com  Support: support@segger.com       *
*                                                                    *
**********************************************************************
*/

// USER START (Optionally insert additional includes)
#include "control.h"
// USER END

#include "DIALOG.h"
#include "stdint.h"
#include "str.h"

/*********************************************************************
*
*       Defines
*
**********************************************************************
*/
#define ID_WINDOW_0 (GUI_ID_USER + 0x00)

#define ID_PROGBAR_0 (GUI_ID_USER + 0x01)

#define ID_BUTTON_0 (GUI_ID_USER + 0x02)
//#define ID_BUTTON_1 (GUI_ID_USER + 0x04)

#define ID_TEXT_0 (GUI_ID_USER + 0x05)
#define ID_TEXT_1 (GUI_ID_USER + 0x06)
#define ID_TEXT_2 (GUI_ID_USER + 0x07)

#define ID_TEXT_3 (GUI_ID_USER + 0x08)
#define ID_TEXT_4 (GUI_ID_USER + 0x09)
#define ID_TEXT_5 (GUI_ID_USER + 0x0a)

// USER START (Optionally insert additional defines)
// USER END

/*********************************************************************
*
*       Static data
*
**********************************************************************
*/

// USER START (Optionally insert additional static data)
// USER END

/*********************************************************************
*
*       _aDialogCreate
*/
static const GUI_WIDGET_CREATE_INFO _aDialogCreate[] = {
  { WINDOW_CreateIndirect, "Window", ID_WINDOW_0, 0, 30, 480, 320, 0, 0x0, 0 },
  { BUTTON_CreateIndirect, "", ID_BUTTON_0, 350, 180, 80, 80, 0, 0x0, 0 },

	{ TEXT_CreateIndirect, "", ID_TEXT_0, 200, 30, 90, 50, 0, 0x0, 0 },//温度
  { TEXT_CreateIndirect, "--", ID_TEXT_1, 200, 90, 90, 50, 0, 0x0, 0 },
	{ TEXT_CreateIndirect, "", ID_TEXT_2, 200, 150, 90, 50, 0, 0x0, 0 },//状态

	{ PROGBAR_CreateIndirect, "Progbar", ID_PROGBAR_0, 20, 25, 80, 230, 1, 0x0, 0 },
	
	{ TEXT_CreateIndirect, "0", ID_TEXT_3, 200, 210, 90, 50, 0, 0x0, 0 },
	
	{ TEXT_CreateIndirect, "", ID_TEXT_4, 380, 30, 90, 50, 0, 0x0, 0 },//OFF 循环开关

	{ TEXT_CreateIndirect, "", ID_TEXT_5, 380, 90, 100, 50, 0, 0x0, 0 },//Connect
	
	
  // USER START (Optionally insert additional widgets)
  // USER END
};

/*********************************************************************
*
*       Static code
*
**********************************************************************
*/

// USER START (Optionally insert additional static code)

extern WM_HWIN Display_set(void);
extern WM_HWIN SelectWindow(void);
extern WM_HWIN SettingWindow(void);

extern GUI_CONST_STORAGE GUI_FONT GUI_FontB24;


WM_HWIN H_Hand;
WM_HTIMER hTimer;

//extern GUI_CONST_STORAGE GUI_BITMAP bmoperate;
extern GUI_CONST_STORAGE GUI_BITMAP bmbasicset;

// USER END

/*********************************************************************
*
*       _cbDialog
*/

// USER START (Optionally insert additional public code)
void BUTTON_Skin()
{
	BUTTON_SKINFLEX_PROPS Props;
	BUTTON_GetSkinFlexProps(&Props, BUTTON_SKINFLEX_PI_ENABLED);
	Props.Radius = 3;
	//Props.aColorFrame[0] = ;
	Props.aColorUpper[0] = GUI_WHITE;
	Props.aColorLower[0] = 0x00DD4040;
	Props.aColorUpper[1] = 0x00DD4040;
	Props.aColorLower[1] = GUI_WHITE;
	BUTTON_SetSkinFlexProps(&Props, BUTTON_SKINFLEX_PI_ENABLED);
	BUTTON_SetSkinFlexProps(&Props, BUTTON_SKINFLEX_PI_FOCUSSED);
	Props.aColorLower[0] = GUI_LIGHTBLUE;
	Props.aColorUpper[1] = GUI_LIGHTBLUE;
	BUTTON_SetSkinFlexProps(&Props, BUTTON_SKINFLEX_PI_PRESSED);
}

void Radio_Skin()
{
	RADIO_SKINFLEX_PROPS Props;
	RADIO_GetSkinFlexProps(&Props, RADIO_SKINFLEX_PI_PRESSED);
	Props.ButtonSize  = 16;
	RADIO_SetSkinFlexProps(&Props, RADIO_SKINFLEX_PI_PRESSED);
	
	RADIO_GetSkinFlexProps(&Props, RADIO_SKINFLEX_PI_UNPRESSED);
	Props.ButtonSize  = 16;
	RADIO_SetSkinFlexProps(&Props, RADIO_SKINFLEX_PI_UNPRESSED);
}


void Progbar_Skin()
{
	PROGBAR_SKINFLEX_PROPS Props;
	PROGBAR_GetSkinFlexProps(&Props, RADIO_SKINFLEX_PI_PRESSED);
	Props.aColorUpperL[0] = Props.aColorLowerL[0];
	Props.aColorLowerL[1] = Props.aColorUpperL[0];
	Props.aColorUpperL[1] = Props.aColorLowerL[1];
	
	Props.aColorUpperR[0] = Props.aColorLowerR[0];
	Props.aColorLowerR[1] = Props.aColorUpperR[0];
	Props.aColorUpperR[1] = Props.aColorLowerR[1];
	//props.
	PROGBAR_SetSkinFlexProps(&Props, RADIO_SKINFLEX_PI_PRESSED);
}


char str_temp[20];

uint8_t propset;
static void _cbDialog(WM_MESSAGE * pMsg) {
	WM_HWIN hItem;
  int NCode;
  int Id;
	int i;
  // USER START (Optionally insert additional variables)
	static uint8_t connect = 0;
	static uint8_t first = 1;
	//降低刷新频率
	uint8_t oldtemp = 0xff;
	uint8_t oldheater = 0xff;
	uint8_t propval = 0xff;
	
	static uint8_t sel = 0;
  // USER END

  switch (pMsg->MsgId) {
	case WM_INIT_DIALOG:	

			hItem = WM_GetDialogItem(pMsg->hWin, ID_BUTTON_0);
			BUTTON_SetFont(hItem,&GUI_FontB24);	
			BUTTON_SetBitmap(hItem,BUTTON_BI_PRESSED,&bmbasicset);
			BUTTON_SetBitmap(hItem,BUTTON_BI_UNPRESSED,&bmbasicset);

			hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_0);
			TEXT_SetFont(hItem,GUI_FONT_24B_1);		
			
			hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_1);
			TEXT_SetTextColor(hItem,GUI_RED);
			TEXT_SetFont(hItem,Set.language?&GUI_FontB24:&GUI_Font20_1);
			
			hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_2);
			TEXT_SetTextColor(hItem,GUI_ORANGE);
			TEXT_SetFont(hItem,Set.language?&GUI_FontB24:&GUI_Font20_1);
			
			hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_3);
			TEXT_SetFont(hItem, GUI_FONT_24B_1);
			TEXT_SetTextColor(hItem, GUI_GREEN);				
			
			hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_4);			
			TEXT_SetFont(hItem,Set.language?&GUI_FontB24:&GUI_Font20_1);
			
			hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_5);			
			TEXT_SetFont(hItem,Set.language?&GUI_FontB24:&GUI_Font20_1);			

			hItem = WM_GetDialogItem(pMsg->hWin, ID_PROGBAR_0);
			PROGBAR_SetMinMax(hItem, 0, 100);
			PROGBAR_SetValue(hItem, 10);//50,85,95

			PROGBAR_SetBarColor(hItem, 0, GUI_GREEN);
			PROGBAR_SetBarColor(hItem, 1, GUI_LIGHTYELLOW);
		break;
	case WM_TIMER:

			//水量
			//Gradual_change
	
			if(State.lowflag == 0)
			{
				if (propset<=8)
					propset+=2;
				if (propset>=12)
					propset-=2;
			}
			else if (State.highflag == 0)
			{
				if (propset<=28)
					propset+=2;
				if (propset>=32)
					propset-=2;
			}
			else if (State.warnflag == 0)
			{
				if (propset<=83)
					propset+=2;
				if (propset>=87)
					propset-=2;
			}
			else
			{
				if (propset<=93)
					propset+=2;
				if (propset>=97)
					propset-=2;
			}	
			if (propval != propset)
			{
				hItem = WM_GetDialogItem(pMsg->hWin, ID_PROGBAR_0);
			//	propval = PROGBAR_GetValue(ID_PROGBAR_0);
				PROGBAR_SetValue(hItem, propset);
			}
			propval = propset;
			
	sel^=1;
		if (sel)//同时刷新会进入hardfault  ？
		{			
			//总流量
			hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_3);
			sprintf((char*)str_temp,"%d",State.totalvolume);
			TEXT_SetText(hItem,str_temp);
		}
		else
		{
			//显示温度
			if (oldtemp != State.temperature)
			{
				hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_0);
				if (State.temperature == 150)
					sprintf((char*)str_temp,"%s","--");
				else if (State.temperature == 151)
					sprintf((char*)str_temp,"%s","XX");
				else	
					sprintf((char*)str_temp,"%d",State.temperature);
				TEXT_SetText(hItem,str_temp);
			}
			oldtemp = State.temperature;
			//加热
			if (oldheater != State.heaterflag)
			{
				hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_1);
				if (State.heaterflag)
				{
					TEXT_SetTextColor(hItem,GUI_RED);
					sprintf((char*)str_temp,String[Find_Str("ON")][Set.language]);
				}
				else
				{
					TEXT_SetTextColor(hItem,GUI_BLACK);
					sprintf((char*)str_temp,String[Find_Str("OFF")][Set.language]);
				}
					TEXT_SetText(hItem,str_temp);
			}
			oldheater = State.heaterflag;
				
			//状态	
			hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_2);
			if (State.inflag)
			{
				sprintf((char*)str_temp,String[Find_Str("Water In")][Set.language]);
			}
			else if (State.outflag)
			{
				sprintf((char*)str_temp,String[Find_Str("Water Out")][Set.language]);
			}
			else
			{
				sprintf((char*)str_temp,String[Find_Str("Standby")][Set.language]);
			}
			TEXT_SetText(hItem,str_temp);
			
			//循环
			hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_4);
			if (Set.circleinterval == 0 || Set.circletime == 0)
			{
				sprintf((char*)str_temp,String[Find_Str(" OFF")][Set.language]);
			}
			else if (State.circleflag)
			{
				sprintf((char*)str_temp,String[Find_Str("Start")][Set.language]);
			}
			else
			{
				sprintf((char*)str_temp,String[Find_Str("Wait")][Set.language]);
			}
			TEXT_SetText(hItem,str_temp);
			//连接			
			hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_5);			
			if (State.connect)
			{
				TEXT_SetTextColor(hItem,GUI_GREEN);
				TEXT_SetText(hItem,String[Find_Str("Connect")][Set.language]);
			}
			else
			{
				TEXT_SetTextColor(hItem,GUI_RED);
				TEXT_SetText(hItem,String[Find_Str("Disconnect")][Set.language]);//connect?"":
				//connect ^= 1 ;
			}
		}
			WM_RestartTimer(pMsg->Data.v, 236);
		break;
			
	case WM_PAINT:
		GUI_DrawGradientV(0,0,479,319,GUI_LIGHTBLUE,GUI_BLUE);
		GUI_SetTextMode(GUI_TM_TRANS);
		GUI_SetFont(GUI_FONT_32B_1);
		GUI_SetColor(GUI_GRAY);
		GUI_DispStringHCenterAt("dotcom",240,65);
	
		GUI_SetColor(GUI_YELLOW);	
		GUI_SetFont(Set.language?&GUI_FontB24:&GUI_Font20_1);
		//GUI_DispStringAt(String[Find_Str("Temperature")][Set.language],140,30);
		if (Set.language == 0)//太长
			GUI_DispStringAt("Temp",140,30);
		else
			GUI_DispStringAt(String[Find_Str("Temperature")][Set.language],140,30);		
		GUI_DispStringAt(String[Find_Str("Heat")][Set.language],140,90);
		GUI_DispStringAt(String[Find_Str("Status")][Set.language],140,150);
		GUI_DispStringAt(String[Find_Str("Flow")][Set.language],140,210);
		GUI_DispStringAt(String[Find_Str("Circle")][Set.language],320,30);
		GUI_SetFont(&GUI_Font20_1);
		GUI_DispStringAt("Drop",320,90);

		GUI_SetFont(GUI_FONT_24B_1);
		GUI_DispStringAt("C",245,30);
	
		GUI_SetFont(GUI_FONT_8_1);
		GUI_DispStringAt("o",240,30);

		//水位
		GUI_SetTextMode(GUI_TM_TRANS);
		GUI_SetFont(GUI_FONT_20_1);
		GUI_SetColor(GUI_GREEN);
		GUI_DispStringAt("--o",100, 200);
		GUI_DispStringAt("--o",100, 60);
		GUI_SetColor(GUI_RED);
		GUI_DispStringAt("--o",100, 30);
		break;
  case WM_NOTIFY_PARENT:
    Id    = WM_GetId(pMsg->hWinSrc);
    NCode = pMsg->Data.v;
    switch(Id) {
    case ID_BUTTON_0: // Notifications sent by 'Status'
      switch(NCode) {
      case WM_NOTIFICATION_CLICKED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      case WM_NOTIFICATION_RELEASED:
        // USER START (Optionally insert code for reacting on notification message)

			WM_DeleteTimer(hTimer);			
				hItem = pMsg->hWin;
				WM_DeleteWindow(hItem);
			if (first)//第一次跳转后,返回主页面会进入hardfault
			{
				first = 0;
				SettingWindow();
			}
			else
				SelectWindow();
        // USER END
        break;
      // USER START (Optionally insert additional code for further notification handling)
      // USER END
      }
      break;
    // USER START (Optionally insert additional code for further Ids)
    // USER END
    }
    break;
  // USER START (Optionally insert additional message handling)
  // USER END
  default:
    WM_DefaultProc(pMsg);
    break;
  }
}

/*********************************************************************
*
*       Public code
*
**********************************************************************
*/
/*********************************************************************
*
*       CreateWindow
*/


WM_HWIN CreateWindow(void);
WM_HWIN CreateWindow(void) {
  WM_HWIN hWin;
	
  hWin = GUI_CreateDialogBox(_aDialogCreate, GUI_COUNTOF(_aDialogCreate), _cbDialog, WM_HBKWIN, 0, 0);
	hTimer = WM_CreateTimer(hWin, 0, 50, 0);
	
  return hWin;
}

void Skin()
{
	Radio_Skin();
	Progbar_Skin();
	BUTTON_Skin();
	GUI_UC_SetEncodeUTF8();
}

void GetFreeRam()
{
	int32_t free,used;
	free = GUI_ALLOC_GetNumFreeBytes();
	used = GUI_ALLOC_GetNumUsedBytes();
	printf("Free = %d,Used = %d\r\n",free,used);
}

/*************************** End of file ****************************/
