/*********************************************************************
*                                                                    *
*                SEGGER Microcontroller GmbH & Co. KG                *
*        Solutions for real time microcontroller applications        *
*                                                                    *
**********************************************************************
*                                                                    *
* C-file generated by:                                               *
*                                                                    *
*        GUI_Builder for emWin version 5.22                          *
*        Compiled Jul  4 2013, 15:16:01                              *
*        (c) 2013 Segger Microcontroller GmbH & Co. KG               *
*                                                                    *
**********************************************************************
*                                                                    *
*        Internet: www.segger.com  Support: support@segger.com       *
*                                                                    *
**********************************************************************
*/

// USER START (Optionally insert additional includes)
// USER END

#include "DIALOG.h"
#include "stdint.h"
/*********************************************************************
*
*       Defines
*
**********************************************************************
*/
#define ID_WINDOW_0 (GUI_ID_USER + 0x00)

#define ID_PROGBAR_0 (GUI_ID_USER + 0x01)

#define ID_BUTTON_0 (GUI_ID_USER + 0x03)
#define ID_BUTTON_1 (GUI_ID_USER + 0x04)

#define ID_TEXT_0 (GUI_ID_USER + 0x05)
#define ID_TEXT_1 (GUI_ID_USER + 0x06)
#define ID_TEXT_2 (GUI_ID_USER + 0x07)

#define ID_TEXT_3 (GUI_ID_USER + 0x08)
#define ID_TEXT_4 (GUI_ID_USER + 0x09)
#define ID_TEXT_5 (GUI_ID_USER + 0x0a)
#define ID_TEXT_6 (GUI_ID_USER + 0x0b)

// USER START (Optionally insert additional defines)
// USER END

/*********************************************************************
*
*       Static data
*
**********************************************************************
*/

// USER START (Optionally insert additional static data)
// USER END

/*********************************************************************
*
*       _aDialogCreate
*/
static const GUI_WIDGET_CREATE_INFO _aDialogCreate[] = {
  { WINDOW_CreateIndirect, "Window", ID_WINDOW_0, 0, 30, 480, 320, 0, 0x0, 0 },

  { BUTTON_CreateIndirect, "Status", ID_BUTTON_0, 350, 40, 80, 80, 0, 0x0, 0 },
  { BUTTON_CreateIndirect, "Setting", ID_BUTTON_1, 350, 180, 80, 80, 0, 0x0, 0 },
	{ TEXT_CreateIndirect, "85", ID_TEXT_0, 200, 30, 90, 50, 0, 0x0, 0 },
  { TEXT_CreateIndirect, "0", ID_TEXT_1, 200, 90, 90, 50, 0, 0x0, 0 },
	{ TEXT_CreateIndirect, "heat", ID_TEXT_2, 200, 150, 90, 50, 0, 0x0, 0 },

	{ PROGBAR_CreateIndirect, "Progbar", ID_PROGBAR_0, 20, 25, 80, 230, 1, 0x0, 0 },
	{ TEXT_CreateIndirect, "--o", ID_TEXT_3, 100, 150, 35, 20, 0, 0x0, 0 },
	{ TEXT_CreateIndirect, "--o", ID_TEXT_4, 100, 50, 35, 20, 0, 0x0, 0 },
	{ TEXT_CreateIndirect, "--o", ID_TEXT_5, 100, 30, 35, 20, 0, 0x0, 0 },
	
	{ TEXT_CreateIndirect, "15000", ID_TEXT_6, 200, 210, 90, 50, 0, 0x0, 0 },
  // USER START (Optionally insert additional widgets)
  // USER END
};

/*********************************************************************
*
*       Static code
*
**********************************************************************
*/

// USER START (Optionally insert additional static code)

extern WM_HWIN Display_set(void);
extern WM_HWIN SelectWindow(void);

extern GUI_CONST_STORAGE GUI_FONT GUI_FontB24;

extern const char *HZStr[];
extern uint8_t Lang_Flag;

WM_HWIN H_Hand;


extern GUI_CONST_STORAGE GUI_BITMAP bmoperate;
extern GUI_CONST_STORAGE GUI_BITMAP bmbasicset;
// USER END

/*********************************************************************
*
*       _cbDialog
*/

// USER START (Optionally insert additional public code)
void Skin()
{
	BUTTON_SKINFLEX_PROPS Props;
	BUTTON_GetSkinFlexProps(&Props, BUTTON_SKINFLEX_PI_ENABLED);
	Props.Radius = 3;
	//Props.aColorFrame[0] = ;
	Props.aColorUpper[0] = GUI_WHITE;
	Props.aColorLower[0] = 0x00DD4040;
	Props.aColorUpper[1] = 0x00DD4040;
	Props.aColorLower[1] = GUI_WHITE;
	BUTTON_SetSkinFlexProps(&Props, BUTTON_SKINFLEX_PI_ENABLED);
	BUTTON_SetSkinFlexProps(&Props, BUTTON_SKINFLEX_PI_FOCUSSED);
	Props.aColorLower[0] = GUI_LIGHTBLUE;
	Props.aColorUpper[1] = GUI_LIGHTBLUE;
	BUTTON_SetSkinFlexProps(&Props, BUTTON_SKINFLEX_PI_PRESSED);
}


static void _cbDialog(WM_MESSAGE * pMsg) {
	WM_HWIN hItem;
  int NCode;
  int Id;
	int i;
  // USER START (Optionally insert additional variables)
  // USER END

  switch (pMsg->MsgId) {
	case WM_INIT_DIALOG:	

			for(i = 0;i < 3;i++)
			{	
				hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_0+i);
				TEXT_SetFont(hItem,GUI_FONT_24B_1);
			}
			for(i = 0;i < 2;i++)
			{
				hItem = WM_GetDialogItem(pMsg->hWin, ID_BUTTON_0+i);
				BUTTON_SetFont(hItem,GUI_FONT_20B_1);	
			}
			
			
			hItem = WM_GetDialogItem(pMsg->hWin, ID_BUTTON_0);
			BUTTON_SetFont(hItem,&GUI_FontB24);	
			//BUTTON_SetText(hItem,"\xE8\xAE\xBE\xE7\xBD\xAE");
	//		BUTTON_SetText(hItem,HZStr[12]);
			BUTTON_SetBitmap(hItem,BUTTON_BI_PRESSED,&bmoperate);
			BUTTON_SetBitmap(hItem,BUTTON_BI_UNPRESSED,&bmoperate);
			
			hItem = WM_GetDialogItem(pMsg->hWin, ID_BUTTON_1);
			BUTTON_SetFont(hItem,&GUI_FontB24);	
	//		BUTTON_SetText(hItem,HZStr[0]);
			BUTTON_SetBitmap(hItem,BUTTON_BI_PRESSED,&bmbasicset);
			BUTTON_SetBitmap(hItem,BUTTON_BI_UNPRESSED,&bmbasicset);
			
			hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_2);
			TEXT_SetTextColor(hItem,GUI_RED);
			TEXT_SetFont(hItem,&GUI_FontB24);
			TEXT_SetText(hItem,HZStr[13]);

			hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_3);
			TEXT_SetFont(hItem, GUI_FONT_20_1);
			TEXT_SetTextColor(hItem, GUI_RED);

			hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_4);
			TEXT_SetFont(hItem, GUI_FONT_20_1);
			TEXT_SetTextColor(hItem, GUI_GREEN);

			hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_5);
			TEXT_SetFont(hItem, GUI_FONT_20_1);
			TEXT_SetTextColor(hItem, GUI_GREEN);

			hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_6);
			TEXT_SetFont(hItem, GUI_FONT_24B_1);
			TEXT_SetTextColor(hItem, GUI_GREEN);

			hItem = WM_GetDialogItem(pMsg->hWin, ID_PROGBAR_0);
			PROGBAR_SetMinMax(hItem, 0, 100);
			PROGBAR_SetValue(hItem, 10);
			PROGBAR_SetValue(hItem, 50);
			PROGBAR_SetValue(hItem, 85);
			PROGBAR_SetValue(hItem, 95);
			PROGBAR_SetBarColor(hItem, 0, GUI_GREEN);
			PROGBAR_SetBarColor(hItem, 1, GUI_LIGHTYELLOW);
		break;
	
	case WM_PAINT:
		GUI_DrawGradientV(0,0,479,319,GUI_LIGHTBLUE,GUI_BLUE);
		GUI_SetTextMode(GUI_TM_TRANS);
		GUI_SetFont(GUI_FONT_32B_1);
		GUI_SetColor(GUI_GRAY);
		GUI_DispStringHCenterAt("dotcom",160,65);
	
		GUI_SetColor(GUI_YELLOW);	

		if (Lang_Flag)
		{
			GUI_SetFont(&GUI_FontB24);
			GUI_DispStringAt(HZStr[1],140,30);
			GUI_DispStringAt(HZStr[13],140,90);	
			GUI_DispStringAt(HZStr[7],140,150);	
			GUI_DispStringAt(HZStr[16], 140, 210);
		}
		else
		{
			GUI_SetFont(GUI_FONT_24B_1);
			GUI_DispStringAt("TEMP",40,40);
			GUI_DispStringAt("Volume",40,100);	
			GUI_DispStringAt("Status",40,160);	
		}
	
		GUI_SetFont(GUI_FONT_24B_1);
		GUI_DispStringAt("C",255,30);
		GUI_DispStringAt("mL",270,210);
	
		GUI_SetFont(GUI_FONT_8_1);
		GUI_DispStringAt("o",250,30);
	/*
		GUI_SetFont(&GUI_Font24);
		GUI_DispStringAt("\xE8\xAE\xBE\xE7\xBD\xAE",40,160);
	
			GUI_SetFont(&GUI_FontB24);
		GUI_DispStringAt("\xE8\xAE\xBE\xE7\xBD\xAE",140,160);
		
				GUI_SetFont(&GUI_FontAA24);
		GUI_DispStringAt("\xE8\xAE\xBE\xE7\xBD\xAE",140,190);
		*/
	
		break;
  case WM_NOTIFY_PARENT:
    Id    = WM_GetId(pMsg->hWinSrc);
    NCode = pMsg->Data.v;
    switch(Id) {
    case ID_BUTTON_0: // Notifications sent by 'Setting'
      switch(NCode) {
      case WM_NOTIFICATION_CLICKED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      case WM_NOTIFICATION_RELEASED:
        // USER START (Optionally insert code for reacting on notification message)
				hItem = pMsg->hWin;
				WM_DeleteWindow(hItem);
						Skin();
			H_Hand = 	Display_set();
        // USER END
        break;
      // USER START (Optionally insert additional code for further notification handling)
      // USER END
      }
      break;
    case ID_BUTTON_1: // Notifications sent by 'Status'
      switch(NCode) {
      case WM_NOTIFICATION_CLICKED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      case WM_NOTIFICATION_RELEASED:
        // USER START (Optionally insert code for reacting on notification message)
				hItem = pMsg->hWin;
				WM_DeleteWindow(hItem);
						Skin();
			SelectWindow();
				//SettingWindow();

        // USER END
        break;
      // USER START (Optionally insert additional code for further notification handling)
      // USER END
      }
      break;
    // USER START (Optionally insert additional code for further Ids)
    // USER END
    }
    break;
  // USER START (Optionally insert additional message handling)
  // USER END
  default:
    WM_DefaultProc(pMsg);
    break;
  }
}

/*********************************************************************
*
*       Public code
*
**********************************************************************
*/
/*********************************************************************
*
*       CreateWindow
*/
WM_HWIN CreateWindow(void);
WM_HWIN CreateWindow(void) {
  WM_HWIN hWin;
		
  hWin = GUI_CreateDialogBox(_aDialogCreate, GUI_COUNTOF(_aDialogCreate), _cbDialog, WM_HBKWIN, 0, 0);

	GUI_UC_SetEncodeUTF8();
  return hWin;
}



/*************************** End of file ****************************/
