/*********************************************************************
*                SEGGER Microcontroller GmbH & Co. KG                *
*        Solutions for real time microcontroller applications        *
*                           www.segger.com                           *
**********************************************************************
*                                                                    *
* C-file generated by                                                *
*                                                                    *
*        emWin Font Converter (ST) version 5.40                      *
*        Compiled Mar 17 2017, 15:34:36                              *
*                                                                    *
*        (c) 1998 - 2017 Segger Microcontroller GmbH & Co. KG        *
*                                                                    *
**********************************************************************
*                                                                    *
* Source file: B24.c                                                 *
* Font:        »ªÎÄËÎÌå                                              *
* Height:      24                                                    *
*                                                                    *
**********************************************************************
*                                                                    *
* Initial font height:  24                                           *
* Range disabled:       0000 - FFFF                                  *
* Read pattern file: C:\Users\IT\Desktop\Font\Heater_unicode.txt     *
*                                                                    *
**********************************************************************
*/

#include "GUI.h"

#ifndef GUI_CONST_STORAGE
  #define GUI_CONST_STORAGE const
#endif

/* The following line needs to be included in any file selecting the
   font.
*/
extern GUI_CONST_STORAGE GUI_FONT GUI_FontB24;

/* Start of unicode area <CJK Unified Ideographs> */
GUI_CONST_STORAGE unsigned char acGUI_FontB24_4F53[ 72] = { /* code 4F53 */
  ________,________,________,
  ________,________,________,
  ________,____XX__,________,
  _____XXX,____XX__,________,
  _____XX_,____XX__,________,
  _____XX_,____XX__,________,
  ____XX__,____XX__,_XXX____,
  ____XXXX,XXXXXXXX,XXXX____,
  ____XXX_,___XXXXX,________,
  ___XXX__,___XXXXX,________,
  __XXXX__,__XXXXXX,________,
  __XXXX__,_XX_XXXX,________,
  _XX_XX__,_XX_XX_X,X_______,
  ____XX__,XX__XX_X,X_______,
  ____XX_X,X___XX_X,XX______,
  ____XXXX,XXXXXXXX,XXX_____,
  ____XXX_,____XX__,_XXX____,
  ____XX__,____XX__,__XXX___,
  ____XX__,____XX__,________,
  ____XX__,____XX__,________,
  ____XX__,____XX__,________,
  ________,________,________,
  ________,________,________,
  ________,________,________};

GUI_CONST_STORAGE unsigned char acGUI_FontB24_4FDD[ 72] = { /* code 4FDD */
  ________,________,________,
  ________,________,________,
  ______XX,________,________,
  _____XXX,XX______,XX______,
  _____XX_,XXXXXXXX,XX______,
  _____XX_,XX______,XX______,
  ____XX__,XX______,XX______,
  ____XX__,XX______,XX______,
  ___XXX__,XX______,XX______,
  ___XXX__,XXXXXXXX,XX______,
  __XXXX__,XX__XX__,XX______,
  _XX_XX__,____XX__,__XX____,
  _XX_XXXX,XXXXXXXX,XXXXX___,
  ____XX__,___XXXXX,________,
  ____XX__,__XXXXXX,________,
  ____XX__,_XX_XX_X,X_______,
  ____XX__,_XX_XX_X,X_______,
  ____XX__,XX__XX__,XXX_____,
  ____XXXX,X___XX__,_XXXX___,
  ____XXX_,____XX__,________,
  ____XX__,____XX__,________,
  ________,________,________,
  ________,________,________,
  ________,________,________};

GUI_CONST_STORAGE unsigned char acGUI_FontB24_4FE1[ 72] = { /* code 4FE1 */
  ________,________,________,
  ________,________,________,
  ______XX,____XX__,________,
  _____XXX,_____XX_,________,
  _____XX_,_____XX_,________,
  _____XX_,________,__XXX___,
  ____XX_X,XXXXXXXX,XXXXX___,
  ____XX__,________,________,
  ___XXX__,________,_XX_____,
  ___XXX__,XXXXXXXX,XXXX____,
  __XXXX__,________,_XX_____,
  __XXXX__,XXXXXXXX,XXXX____,
  _XX_XX__,________,________,
  ____XX__,_XX_____,_XX_____,
  ____XX__,_XXXXXXX,XXXX____,
  ____XX__,_XX_____,_XX_____,
  ____XX__,_XX_____,_XX_____,
  ____XX__,_XX_____,_XX_____,
  ____XX__,_XXXXXXX,XXX_____,
  ____XX__,_XX_____,_XX_____,
  ____XX__,_XX_____,_XX_____,
  ________,________,________,
  ________,________,________,
  ________,________,________};

GUI_CONST_STORAGE unsigned char acGUI_FontB24_505C[ 72] = { /* code 505C */
  ________,________,________,
  ________,________,________,
  _____XXX,___XXX__,________,
  _____XX_,____XXX_,________,
  _____XX_,____XX__,__XX____,
  ____XXXX,XXXXXXXX,XXXXX___,
  ____XX__,_XX_____,XX______,
  ____XX__,_XXXXXXX,XX______,
  ___XXX__,_XX_____,XX______,
  __XXXX__,_XXXXXXX,XX______,
  __XXXX_X,XXX_____,XX_XX___,
  _XX_XX_X,XXXXXXXX,XXXXXX__,
  ____XX_X,X_______,__XX____,
  ____XXXX,X_______,_XX_____,
  ____XX__,XXXXXXXX,XXXX____,
  ____XX__,_____XX_,________,
  ____XX__,_____XX_,________,
  ____XX__,_____XX_,________,
  ____XX__,_____XX_,________,
  ____XX__,_XXX_XX_,________,
  ____XX__,___XXXX_,________,
  ________,____XX__,________,
  ________,________,________,
  ________,________,________};

GUI_CONST_STORAGE unsigned char acGUI_FontB24_51FB[ 72] = { /* code 51FB */
  ________,________,________,
  ________,________,________,
  ________,__XX____,________,
  ________,__XX____,________,
  ________,__XX____,________,
  ________,__XX____,XX______,
  ___XXXXX,XXXXXXXX,XXX_____,
  ________,__XX____,________,
  ________,__XX____,________,
  ________,__XX____,________,
  ________,__XX____,__XXX___,
  _XXXXXXX,XXXXXXXX,XXXXX___,
  ________,__XX____,________,
  ____XXX_,__XX____,XXX_____,
  ____XX__,__XX____,XX______,
  ____XX__,__XX____,XX______,
  ____XX__,__XX____,XX______,
  ____XX__,__XX____,XX______,
  ____XX__,__XX____,XX______,
  ___XXXXX,XXXXXXXX,XX______,
  ____XX__,________,XX______,
  ________,________,________,
  ________,________,________,
  ________,________,________};

GUI_CONST_STORAGE unsigned char acGUI_FontB24_52A0[ 72] = { /* code 52A0 */
  ________,________,________,
  ________,________,________,
  _____XX_,________,________,
  _____XX_,________,________,
  _____XX_,________,________,
  _____XX_,____XX__,__XX____,
  _____XX_,_XX_XXXX,XXXXX___,
  __XXXXXX,XXXXXX__,__XX____,
  _____XX_,_XX_XX__,__XX____,
  _____XX_,_XX_XX__,__XX____,
  _____XX_,_XX_XX__,__XX____,
  ____XX__,_XX_XX__,__XX____,
  ____XX__,_XX_XX__,__XX____,
  ____XX__,_XX_XX__,__XX____,
  ____XX__,_XX_XX__,__XX____,
  ____XX__,_XX_XX__,__XX____,
  ___XX___,XXX_XX__,__XX____,
  ___XX___,XX__XXXX,XXXX____,
  ___XX___,XX__XX__,__XX____,
  __XX_XXX,XX__XX__,__XX____,
  _XX____X,X___XX__,________,
  ________,________,________,
  ________,________,________,
  ________,________,________};

GUI_CONST_STORAGE unsigned char acGUI_FontB24_52A8[ 72] = { /* code 52A8 */
  ________,________,________,
  ________,________,________,
  ________,_____XXX,________,
  ________,_____XX_,________,
  ________,_XX__XX_,________,
  __XXXXXX,XXX__XX_,________,
  ________,_____XX_,__XX____,
  ________,__XXXXXX,XXXXX___,
  ________,_XX__XX_,__XX____,
  _XXXXXXX,XXXX_XX_,__XX____,
  _____XXX,_____XX_,__XX____,
  _____XX_,_____XX_,__XX____,
  ____XX_X,X____XX_,__XX____,
  ____XX__,XX__XX__,__XX____,
  ___XX___,XX__XX__,__XX____,
  ___XX___,_XX_XX__,__XX____,
  __XXXXXX,XXXXX___,__XX____,
  __XXX___,_XXXX___,_XXX____,
  ________,__XX____,_XX_____,
  ________,XXX___XX,XXX_____,
  _______X,X_______,XX______,
  ______XX,________,________,
  ________,________,________,
  ________,________,________};

GUI_CONST_STORAGE unsigned char acGUI_FontB24_5355[ 72] = { /* code 5355 */
  ________,________,________,
  ________,________,________,
  ______XX,______XX,X_______,
  _______X,X____XX_,________,
  ____XX_X,XX__XX__,_XX_____,
  ____XXXX,XXXXXXXX,XXXX____,
  ____XX__,__XX____,_XX_____,
  ____XX__,__XX____,_XX_____,
  ____XX__,__XX____,_XX_____,
  ____XXXX,XXXXXXXX,XXX_____,
  ____XX__,__XX____,_XX_____,
  ____XX__,__XX____,_XX_____,
  ____XXXX,XXXXXXXX,XXX_____,
  ____XX__,__XX____,_XX_____,
  ________,__XX____,________,
  ________,__XX____,__XX____,
  _XXXXXXX,XXXXXXXX,XXXXX___,
  ________,__XX____,________,
  ________,__XX____,________,
  ________,__XX____,________,
  ________,__XX____,________,
  ________,__XX____,________,
  ________,________,________,
  ________,________,________};

GUI_CONST_STORAGE unsigned char acGUI_FontB24_53CC[ 72] = { /* code 53CC */
  ________,________,________,
  ________,________,________,
  ________,________,________,
  ________,XX______,_XX_____,
  _XXXXXXX,XXXXXXXX,XXXX____,
  ________,XX_XX___,_XX_____,
  ________,XX_XX___,_XX_____,
  __XX___X,X__XX___,XX______,
  ___XX__X,X__XX___,XX______,
  ____XX_X,X__XXX__,XX______,
  _____XXX,X___XX__,XX______,
  _____XXX,____XX_X,X_______,
  ______XX,____XX_X,X_______,
  _____XXX,X___XXXX,________,
  _____XXX,X____XX_,________,
  ____XX_X,XX___XXX,________,
  ___XX___,XX__XXXX,X_______,
  ___XX___,XXXXX__X,XX______,
  __XX____,_XX_____,XXXX____,
  _XX____X,XX______,_XX_____,
  _____XXX,________,________,
  ________,________,________,
  ________,________,________,
  ________,________,________};

GUI_CONST_STORAGE unsigned char acGUI_FontB24_53D6[ 72] = { /* code 53D6 */
  ________,________,________,
  ________,________,________,
  ________,___XX___,________,
  _XXXXXXX,XXXXX___,________,
  ___XX___,XX______,XX______,
  ___XX___,XXXXXXXX,XXX_____,
  ___XX___,XX_XX___,_XX_____,
  ___XXXXX,XX_XX___,XX______,
  ___XX___,XX_XX___,XX______,
  ___XX___,XX_XXX__,XX______,
  ___XX___,XX__XX__,XX______,
  ___XXXXX,XX__XX_X,X_______,
  ___XX___,XX__XXXX,X_______,
  ___XX___,XX___XXX,X_______,
  ___XX___,XXXXXXXX,________,
  ___XX_XX,XX___XXX,________,
  __XXXXX_,XX___XXX,X_______,
  _XX_____,XX__XX_X,XX______,
  ________,XX_XX___,XXXX____,
  ________,XXXX____,________,
  ________,XXX_____,________,
  ________,________,________,
  ________,________,________,
  ________,________,________};

GUI_CONST_STORAGE unsigned char acGUI_FontB24_56DE[ 72] = { /* code 56DE */
  ________,________,________,
  ________,________,________,
  ________,________,________,
  ___XX___,________,_XXX____,
  ___XXXXX,XXXXXXXX,XXX_____,
  ___XX___,________,_XX_____,
  ___XX___,________,_XX_____,
  ___XX__X,X____XX_,_XX_____,
  ___XX__X,XXXXXXXX,_XX_____,
  ___XX__X,X____XX_,_XX_____,
  ___XX__X,X____XX_,_XX_____,
  ___XX__X,X____XX_,_XX_____,
  ___XX__X,X____XX_,_XX_____,
  ___XX__X,XXXXXXX_,_XX_____,
  ___XX__X,X____XX_,_XX_____,
  ___XX__X,X_______,_XX_____,
  ___XX___,________,_XX_____,
  ___XXXXX,XXXXXXXX,XXX_____,
  ___XX___,________,_XX_____,
  ___XX___,________,_XX_____,
  ___XX___,________,________,
  ________,________,________,
  ________,________,________,
  ________,________,________};

GUI_CONST_STORAGE unsigned char acGUI_FontB24_59CB[ 72] = { /* code 59CB */
  ________,________,________,
  ________,________,________,
  _____XXX,______XX,________,
  _____XX_,______XX,________,
  _____XX_,_____XX_,________,
  _____XX_,_____XX_,________,
  _____XX_,XX__XX__,XX______,
  __XXXXXX,XX_XX___,_XX_____,
  ____XX__,XX_XX___,__XX____,
  ____XX__,XXXXXXXX,XXXXX___,
  ____XX__,XXXXXX__,___XX___,
  ____XX__,XX______,___XX___,
  ____XX_X,X__XX___,_XX_____,
  ___XX__X,X__XXXXX,XXXX____,
  ___XX__X,X__XX___,_XX_____,
  ____XXXX,___XX___,_XX_____,
  _____XXX,___XX___,_XX_____,
  _____XXX,XX_XX___,_XX_____,
  ____XX__,XX_XXXXX,XXX_____,
  ___XX___,XX_XX___,_XX_____,
  __XX____,___XX___,_XX_____,
  ________,________,________,
  ________,________,________,
  ________,________,________};

GUI_CONST_STORAGE unsigned char acGUI_FontB24_5EA6[ 72] = { /* code 5EA6 */
  ________,________,________,
  ________,________,________,
  ________,__XXX___,________,
  ________,___XX___,________,
  ___XX___,________,_XXX____,
  ___XXXXX,XXXXXXXX,XXXX____,
  ___XX___,_XX___XX,________,
  ___XX___,_XX___XX,__XX____,
  ___XX_XX,XXXXXXXX,XXXXX___,
  ___XX___,_XX___XX,________,
  ___XX___,_XX___XX,________,
  ___XX___,_XXXXXXX,________,
  ___XX___,_XX___XX,________,
  ___XX_XX,XXXXXXXX,X_______,
  ___XX___,XX____XX,________,
  ___XX___,_XX__XX_,________,
  __XX____,_XX__XX_,________,
  __XX____,__XXXX__,________,
  __XX____,___XXXX_,________,
  _XX_____,_XXX_XXX,XXX_____,
  _XX___XX,XX______,XXXX____,
  ___XXXX_,________,________,
  ________,________,________,
  ________,________,________};

GUI_CONST_STORAGE unsigned char acGUI_FontB24_5F00[ 72] = { /* code 5F00 */
  ________,________,________,
  ________,________,________,
  ________,________,________,
  ________,________,_XX_____,
  __XXXXXX,XXXXXXXX,XXXX____,
  _______X,X____XX_,________,
  _______X,X____XX_,________,
  _______X,X____XX_,________,
  _______X,X____XX_,________,
  _______X,X____XX_,__XX____,
  _XXXXXXX,XXXXXXXX,XXXXX___,
  _______X,X____XX_,________,
  _______X,X____XX_,________,
  _______X,X____XX_,________,
  _______X,X____XX_,________,
  ______XX,_____XX_,________,
  ______XX,_____XX_,________,
  _____XX_,_____XX_,________,
  ____XX__,_____XX_,________,
  ___XX___,_____XX_,________,
  __XX____,_____XX_,________,
  ________,________,________,
  ________,________,________,
  ________,________,________};

GUI_CONST_STORAGE unsigned char acGUI_FontB24_6001[ 72] = { /* code 6001 */
  ________,________,________,
  ________,________,________,
  ________,__XX____,________,
  ________,__XX____,________,
  ________,__XX____,________,
  ________,_XX_____,_XXX____,
  _XXXXXXX,XXXXXXXX,XXXX____,
  ________,_XX_XX__,________,
  ________,_XX_XX__,________,
  ________,XX___XX_,________,
  _______X,XX___XX_,________,
  _______X,XXXX__XX,________,
  _____XXX,__XXX__X,XX______,
  ____XX__,________,XXXXX___,
  __XXX__X,X_XX____,__XX____,
  _XX_XX_X,X__XX___,_XX_____,
  ____XX_X,X__XX__X,XXXX____,
  ___XX__X,X______X,X_XXX___,
  __XXX__X,X______X,X__XX___,
  __XX___X,X______X,XX______,
  _______X,XXXXXXXX,X_______,
  ________,________,________,
  ________,________,________,
  ________,________,________};

GUI_CONST_STORAGE unsigned char acGUI_FontB24_606F[ 72] = { /* code 606F */
  ________,________,________,
  ________,________,________,
  ________,_XXX____,________,
  ________,_XX_____,________,
  ____XX__,XX______,XX______,
  ____XXXX,XXXXXXXX,XXX_____,
  ____XX__,________,XX______,
  ____XXXX,XXXXXXXX,XX______,
  ____XX__,________,XX______,
  ____XX__,________,XX______,
  ____XXXX,XXXXXXXX,XX______,
  ____XX__,________,XX______,
  ____XX__,________,XX______,
  ____XXXX,XXXXXXXX,XX______,
  ____XX__,________,XX______,
  ______XX,__XX____,________,
  ______XX,___XX___,_XX_____,
  ___XX_XX,___XX_XX,__XX____,
  ___XX_XX,______XX,___XX___,
  _XXX__XX,______XX,X__XX___,
  ______XX,XXXXXXXX,________,
  ________,________,________,
  ________,________,________,
  ________,________,________};

GUI_CONST_STORAGE unsigned char acGUI_FontB24_624B[ 72] = { /* code 624B */
  ________,________,________,
  ________,________,________,
  ________,________,________,
  ________,___XXXXX,XX______,
  __XXXXXX,XXXX____,________,
  ________,__XX____,________,
  ________,__XX____,________,
  ________,__XX____,XX______,
  ___XXXXX,XXXXXXXX,XXX_____,
  ________,__XX____,________,
  ________,__XX____,________,
  ________,__XX____,__XX____,
  _XXXXXXX,XXXXXXXX,XXXXX___,
  ________,__XX____,________,
  ________,__XX____,________,
  ________,__XX____,________,
  ________,__XX____,________,
  ________,__XX____,________,
  ________,__XX____,________,
  ________,XXXX____,________,
  ________,_XXX____,________,
  ________,________,________,
  ________,________,________,
  ________,________,________};

GUI_CONST_STORAGE unsigned char acGUI_FontB24_6B62[ 72] = { /* code 6B62 */
  ________,________,________,
  ________,________,________,
  ________,___XX___,________,
  ________,___XX___,________,
  ________,___XX___,________,
  ________,___XX___,________,
  _____XX_,___XX___,________,
  _____XX_,___XX___,________,
  _____XX_,___XX___,________,
  _____XX_,___XX___,XXX_____,
  _____XX_,___XXXXX,XXX_____,
  _____XX_,___XX___,________,
  _____XX_,___XX___,________,
  _____XX_,___XX___,________,
  _____XX_,___XX___,________,
  _____XX_,___XX___,________,
  _____XX_,___XX___,________,
  _____XX_,___XX___,________,
  _____XX_,___XX___,__XX____,
  _XXXXXXX,XXXXXXXX,XXXXX___,
  ________,________,________,
  ________,________,________,
  ________,________,________,
  ________,________,________};

GUI_CONST_STORAGE unsigned char acGUI_FontB24_6C34[ 72] = { /* code 6C34 */
  ________,________,________,
  ________,________,________,
  ________,__XX____,________,
  ________,__XX____,________,
  ________,__XX____,________,
  ________,__XX____,________,
  ________,__XXX___,XXX_____,
  _______X,X_XXX__X,XX______,
  _XXXXXXX,XXXXX_XX,X_______,
  _______X,X_XXXXX_,________,
  ______XX,X_XXXX__,________,
  ______XX,__XX_XX_,________,
  ______XX,__XX_XX_,________,
  _____XX_,__XX__XX,________,
  _____XX_,__XX__XX,________,
  ____XX__,__XX___X,X_______,
  ____XX__,__XX____,XX______,
  ___XX___,__XX____,XXXX____,
  __XX____,__XX____,_XXX____,
  _XX____X,X_XX____,________,
  ________,XXXX____,________,
  ________,________,________,
  ________,________,________,
  ________,________,________};

GUI_CONST_STORAGE unsigned char acGUI_FontB24_6D41[ 72] = { /* code 6D41 */
  ________,________,________,
  ________,________,________,
  ________,___XX___,________,
  ___XX___,____XXX_,________,
  ____XX__,____XX__,__XX____,
  ____XXXX,XXXXXXXX,XXXXX___,
  ______XX,___XXXXX,________,
  ______XX,__XXX__X,XX______,
  _XXX_XX_,_XX_____,XXX_____,
  __XXXXXX,XXXXXXXX,XXXX____,
  ___XXXX_,________,_XX_____,
  ____XX__,________,________,
  ____XX__,XXX_XXXX,XX______,
  ____XX__,XX__XX_X,X_______,
  ___XX___,XX__XX_X,X_______,
  _XXXX___,XX__XX_X,X_______,
  ___XX___,XX__XX_X,X_XX____,
  ___XX___,XX__XX_X,X_XX____,
  ___XX___,XX__XX_X,X_XX____,
  ___XX__X,X___XX_X,X_XXX___,
  ___XX_XX,____XX_X,XXXXX___,
  _____XX_,________,________,
  ________,________,________,
  ________,________,________};

GUI_CONST_STORAGE unsigned char acGUI_FontB24_6D88[ 72] = { /* code 6D88 */
  ________,________,________,
  ________,________,________,
  ________,_____XXX,________,
  ____XX__,XX___XX_,__XX____,
  _____XX_,_XXX_XX_,_XX_____,
  _____XX_,__XXXXX_,XX______,
  _______X,X__XXXX_,XX______,
  _XX____X,XXX__XX_,__XX____,
  __XXX_XX,_XXXXXXX,XXXXX___,
  ___XX_XX,_XX_____,__XX____,
  ______XX,_XX_____,__XX____,
  _____XX_,_XXXXXXX,XXXX____,
  _____XX_,_XX_____,__XX____,
  _____XX_,_XX_____,__XX____,
  ____XX__,_XX_____,__XX____,
  __XXXX__,_XXXXXXX,XXXX____,
  ____XX__,_XX_____,__XX____,
  ____XX__,_XX_____,__XX____,
  ____XX__,_XX_____,__XX____,
  ____XX__,_XX____X,X_XX____,
  ____XX__,_XX_____,XXXX____,
  ________,________,_XX_____,
  ________,________,________,
  ________,________,________};

GUI_CONST_STORAGE unsigned char acGUI_FontB24_6E29[ 72] = { /* code 6E29 */
  ________,________,________,
  ________,________,________,
  ________,________,________,
  ___XX___,XXXXXXXX,XXX_____,
  ____XX__,XX______,XX______,
  ____XXXX,XX______,XX______,
  ______XX,XXXXXXXX,XX______,
  ______XX,XX______,XX______,
  __XXXXX_,XX______,XX______,
  ___XXXX_,XX______,XX______,
  _____XX_,XXXXXXXX,XX______,
  ____XX__,XX______,XXX_____,
  ____XX_X,XXXXXXXX,XXX_____,
  ____XX_X,X_XX_XX_,_XX_____,
  ___XX__X,X_XX_XX_,_XX_____,
  __XXX__X,X_XX_XX_,_XX_____,
  ___XX__X,X_XX_XX_,_XX_____,
  ___XX__X,X_XX_XX_,_XX_____,
  ___XX__X,X_XX_XX_,_XXXX___,
  ___XXXXX,XXXXXXXX,XXXXX___,
  ___XX___,________,________,
  ________,________,________,
  ________,________,________,
  ________,________,________};

GUI_CONST_STORAGE unsigned char acGUI_FontB24_70ED[ 72] = { /* code 70ED */
  ________,________,________,
  ________,________,________,
  _____XX_,____XX__,________,
  _____XX_,____XX__,________,
  _____XX_,____XX__,________,
  _____XX_,XX__XX_X,X_______,
  _XXXXXXX,XXXXXXXX,XX______,
  _____XX_,____XX_X,X_______,
  _____XX_,XX__XX_X,X_______,
  _____XXX,XXXXXX_X,X_______,
  ____XXX_,___XX__X,X_______,
  _XXXXXX_,___XXX_X,X_XX____,
  _____XX_,___XXXXX,X_XX____,
  _____XX_,__XX_XX_,XXXX____,
  __XXXXX_,_XX_____,XXXX____,
  ____XXX_,XX______,_XXX____,
  ________,________,________,
  ____XX__,____XX__,XX______,
  ____XX_X,X___XX__,_XX_____,
  ___XXX__,XX___XX_,_XXX____,
  _XXXX___,XX______,__XX____,
  ________,________,________,
  ________,________,________,
  ________,________,________};

GUI_CONST_STORAGE unsigned char acGUI_FontB24_72B6[ 72] = { /* code 72B6 */
  ________,________,________,
  ________,________,________,
  ______XX,____XXX_,________,
  ______XX,____XX_X,X_______,
  ______XX,____XX__,XX______,
  _XX___XX,____XX__,_XX_____,
  __XX__XX,____XX__,_XX_____,
  ___XX_XX,____XX__,__XX____,
  ___XX_XX,XXXXXXXX,XXXXX___,
  ___XX_XX,____XXX_,________,
  ______XX,____XXX_,________,
  _____XXX,____XXXX,________,
  ____XXXX,___XX_XX,________,
  ___XX_XX,___XX_XX,________,
  __XX__XX,___XX_XX,________,
  _XXX__XX,___XX__X,X_______,
  ______XX,__XX___X,XX______,
  ______XX,__XX____,XX______,
  ______XX,_XX_____,_XXX____,
  ______XX,XX______,_XXX____,
  ______XX,X_______,________,
  ________,________,________,
  ________,________,________,
  ________,________,________};

GUI_CONST_STORAGE unsigned char acGUI_FontB24_786E[ 72] = { /* code 786E */
  ________,________,________,
  ________,________,________,
  ________,____XXX_,________,
  ________,____XX__,________,
  ________,XX_XXX__,XX______,
  __XXXXXX,XXXXXXXX,XXX_____,
  _____XX_,__XXX__X,X_______,
  _____XX_,_XXX__XX,__XX____,
  ____XX__,XXXXXXXX,XXXXX___,
  ____XX_X,X_XX__XX,__XX____,
  ____XXXX,X_XX__XX,__XX____,
  ___XXX_X,X_XXXXXX,XXXX____,
  ___XXX_X,X_XX__XX,__XX____,
  __XXXX_X,X_XX__XX,__XX____,
  _XX_XX_X,X_XXXXXX,XXXX____,
  ____XX_X,X_XX__XX,__XX____,
  ____XXXX,X_XX__XX,__XX____,
  ____XX_X,XXX___XX,__XX____,
  ____XX__,_XX___XX,__XX____,
  ____XX__,XX____XX,XXXX____,
  _______X,X_______,_XXX____,
  ______XX,________,________,
  ________,________,________,
  ________,________,________};

GUI_CONST_STORAGE unsigned char acGUI_FontB24_79EF[ 72] = { /* code 79EF */
  ________,________,________,
  ________,________,________,
  ________,XX______,________,
  ______XX,XXXXX___,_XX_____,
  __XXXXX_,___XXXXX,XXX_____,
  _____XX_,___XX___,_XX_____,
  _____XX_,___XX___,_XX_____,
  _____XX_,XX_XX___,_XX_____,
  _XXXXXXX,XXXXX___,_XX_____,
  _____XX_,___XX___,_XX_____,
  ____XXXX,___XX___,_XX_____,
  ____XXXX,X__XXXXX,XXX_____,
  ___XXXX_,XX_XX___,_XX_____,
  ___XXXX_,XX______,_XX_____,
  __XX_XX_,____XX__,________,
  __XX_XX_,___XXX__,XX______,
  _XX__XX_,___XX___,_XX_____,
  _____XX_,__XX____,__XX____,
  _____XX_,_XX_____,__XXX___,
  _____XX_,XX______,___XX___,
  _____XXX,X_______,________,
  ________,________,________,
  ________,________,________,
  ________,________,________};

GUI_CONST_STORAGE unsigned char acGUI_FontB24_7F6E[ 72] = { /* code 7F6E */
  ________,________,________,
  ________,________,________,
  ________,________,_XX_____,
  ___XXXXX,XXXXXXXX,XXXX____,
  ___XX___,XX__XX__,_XX_____,
  ___XX___,XX__XX__,_XX_____,
  ___XX___,XX__XX__,_XX_____,
  ___XXXXX,XXXXXXXX,XXX_____,
  ___XX___,__XX____,_XXX____,
  _XXXXXXX,XXXXXXXX,XXXXX___,
  _____XX_,_XX____X,X_______,
  _____XXX,XXXXXXXX,XX______,
  _____XX_,_______X,X_______,
  _____XXX,XXXXXXXX,X_______,
  _____XX_,_______X,X_______,
  _____XXX,XXXXXXXX,X_______,
  _____XX_,_______X,X_______,
  _____XXX,XXXXXXXX,X_______,
  _____XX_,_______X,X_XX____,
  _XXXXXXX,XXXXXXXX,XXXXX___,
  ________,________,________,
  ________,________,________,
  ________,________,________,
  ________,________,________};

GUI_CONST_STORAGE unsigned char acGUI_FontB24_8865[ 72] = { /* code 8865 */
  ________,________,________,
  ________,________,________,
  _____XX_,______XX,________,
  _____XXX,______XX,________,
  ______XX,______XX,________,
  ________,______XX,________,
  __XXXXXX,XXX___XX,________,
  ________,XX____XX,________,
  _______X,X_____XX,X_______,
  _______X,X_XX__XX,XXX_____,
  ______XX,_XX___XX,__XX____,
  _____XXX,XX____XX,___XX___,
  ____XXXX,XX____XX,___XX___,
  ___XX_XX,_XX___XX,________,
  __XX__XX,______XX,________,
  _XX___XX,______XX,________,
  ______XX,______XX,________,
  ______XX,______XX,________,
  ______XX,______XX,________,
  ______XX,______XX,________,
  ______XX,______XX,________,
  ________,________,________,
  ________,________,________,
  ________,________,________};

GUI_CONST_STORAGE unsigned char acGUI_FontB24_8BA4[ 72] = { /* code 8BA4 */
  ________,________,________,
  ________,________,________,
  ________,____XX__,________,
  ____XX__,____XXX_,________,
  _____XX_,____XXX_,________,
  _____XXX,____XXX_,________,
  _____XX_,____XXX_,________,
  ________,____XXX_,________,
  ____XX__,____XXX_,________,
  _XXXXXX_,____XXX_,________,
  ____XX__,____XXX_,________,
  ____XX__,___XXXX_,________,
  ____XX__,___XX_XX,________,
  ____XX__,_XXXX_XX,________,
  ____XX__,XX_XX_XX,________,
  ____XX_X,X_XX___X,X_______,
  ____XXXX,__XX___X,X_______,
  ____XXX_,_XX_____,XX______,
  ____XX__,XX______,XXX_____,
  ____XX_X,X_______,_XXXX___,
  ______XX,________,________,
  ________,________,________,
  ________,________,________,
  ________,________,________};

GUI_CONST_STORAGE unsigned char acGUI_FontB24_8BBE[ 72] = { /* code 8BBE */
  ________,________,________,
  ________,________,________,
  ___XX___,________,________,
  ____XX__,__XXXXXX,XX______,
  ____XXX_,__XX___X,X_______,
  _____XX_,__XX___X,X_______,
  ________,__XX___X,X_______,
  ________,__XX___X,X_______,
  ____XX__,_XX____X,XXXXX___,
  _XXXXXX_,_XX_____,________,
  ____XX_X,XX______,________,
  ____XX__,_XXXXXXX,XX______,
  ____XX__,__XX___X,X_______,
  ____XX__,__XX___X,X_______,
  ____XX__,__XX__XX,________,
  ____XX__,___XX_XX,________,
  ____XX_X,X___XXX_,________,
  ____XXXX,____XXX_,________,
  ____XXX_,___XX_XX,X_______,
  ___XXX__,_XXX____,XXXXX___,
  _______X,XX______,________,
  ________,________,________,
  ________,________,________,
  ________,________,________};

GUI_CONST_STORAGE unsigned char acGUI_FontB24_8FD4[ 72] = { /* code 8FD4 */
  ________,________,________,
  ________,________,________,
  ________,________,________,
  ___XX___,_______X,XXX_____,
  ____XX__,_XXXXXXX,________,
  ____XXX_,_XXX____,________,
  _____XX_,_XX_____,________,
  ________,_XX_____,XX______,
  ________,_XXXXXXX,XXX_____,
  ____XX__,_XX_____,XX______,
  _XXXXXX_,_XX_____,XX______,
  ____XX__,_XXXX__X,X_______,
  ____XX__,_XX_XX_X,X_______,
  ____XX__,XX___XXX,________,
  ____XX__,XX___XXX,X_______,
  ____XX__,XX__XXX_,XXX_____,
  ____XX_X,X__XX___,_XX_____,
  ___XXXXX,_XXX____,_XX_____,
  __XX_XX_,________,___XX___,
  _XXX__XX,________,XXXX____,
  _______X,XXXXXXXX,XXXX____,
  ________,________,________,
  ________,________,________,
  ________,________,________};

GUI_CONST_STORAGE unsigned char acGUI_FontB24_91CF[ 72] = { /* code 91CF */
  ________,________,________,
  ________,________,________,
  ____XX__,________,XX______,
  ____XXXX,XXXXXXXX,XXX_____,
  ____XX__,________,XX______,
  ____XXXX,XXXXXXXX,XX______,
  ____XX__,________,XX______,
  ____XXXX,XXXXXXXX,XX______,
  ____XX__,________,XXXX____,
  _XXXXXXX,XXXXXXXX,XXXXX___,
  ____XX__,________,XX______,
  ____XXXX,XXXXXXXX,XXX_____,
  ____XX__,__XX____,XX______,
  ____XXXX,XXXXXXXX,XX______,
  ____XX__,__XX____,XX______,
  ____XXXX,XXXXXXXX,XX______,
  ____XX__,__XX____,XX______,
  ____XXXX,XXXXXXXX,XXX_____,
  ________,__XX____,________,
  ________,__XX____,__XX____,
  _XXXXXXX,XXXXXXXX,XXXXX___,
  ________,________,________,
  ________,________,________,
  ________,________,________};

GUI_CONST_STORAGE GUI_CHARINFO GUI_FontB24_CharInfo[32] = {
   {  22,  22,  3, acGUI_FontB24_4F53 } /* code 4F53 */
  ,{  22,  22,  3, acGUI_FontB24_4FDD } /* code 4FDD */
  ,{  22,  22,  3, acGUI_FontB24_4FE1 } /* code 4FE1 */
  ,{  22,  22,  3, acGUI_FontB24_505C } /* code 505C */
  ,{  22,  22,  3, acGUI_FontB24_51FB } /* code 51FB */
  ,{  22,  22,  3, acGUI_FontB24_52A0 } /* code 52A0 */
  ,{  22,  22,  3, acGUI_FontB24_52A8 } /* code 52A8 */
  ,{  22,  22,  3, acGUI_FontB24_5355 } /* code 5355 */
  ,{  22,  22,  3, acGUI_FontB24_53CC } /* code 53CC */
  ,{  22,  22,  3, acGUI_FontB24_53D6 } /* code 53D6 */
  ,{  22,  22,  3, acGUI_FontB24_56DE } /* code 56DE */
  ,{  22,  22,  3, acGUI_FontB24_59CB } /* code 59CB */
  ,{  22,  22,  3, acGUI_FontB24_5EA6 } /* code 5EA6 */
  ,{  22,  22,  3, acGUI_FontB24_5F00 } /* code 5F00 */
  ,{  22,  22,  3, acGUI_FontB24_6001 } /* code 6001 */
  ,{  22,  22,  3, acGUI_FontB24_606F } /* code 606F */
  ,{  22,  22,  3, acGUI_FontB24_624B } /* code 624B */
  ,{  22,  22,  3, acGUI_FontB24_6B62 } /* code 6B62 */
  ,{  22,  22,  3, acGUI_FontB24_6C34 } /* code 6C34 */
  ,{  22,  22,  3, acGUI_FontB24_6D41 } /* code 6D41 */
  ,{  22,  22,  3, acGUI_FontB24_6D88 } /* code 6D88 */
  ,{  22,  22,  3, acGUI_FontB24_6E29 } /* code 6E29 */
  ,{  22,  22,  3, acGUI_FontB24_70ED } /* code 70ED */
  ,{  22,  22,  3, acGUI_FontB24_72B6 } /* code 72B6 */
  ,{  22,  22,  3, acGUI_FontB24_786E } /* code 786E */
  ,{  22,  22,  3, acGUI_FontB24_79EF } /* code 79EF */
  ,{  22,  22,  3, acGUI_FontB24_7F6E } /* code 7F6E */
  ,{  22,  22,  3, acGUI_FontB24_8865 } /* code 8865 */
  ,{  22,  22,  3, acGUI_FontB24_8BA4 } /* code 8BA4 */
  ,{  22,  22,  3, acGUI_FontB24_8BBE } /* code 8BBE */
  ,{  22,  22,  3, acGUI_FontB24_8FD4 } /* code 8FD4 */
  ,{  22,  22,  3, acGUI_FontB24_91CF } /* code 91CF */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_FontB24_Prop32 = {
   0x91CF /* first character */
  ,0x91CF /* last character  */
  ,&GUI_FontB24_CharInfo[ 31] /* address of first character */
  ,(GUI_CONST_STORAGE GUI_FONT_PROP *)0 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_FontB24_Prop31 = {
   0x8FD4 /* first character */
  ,0x8FD4 /* last character  */
  ,&GUI_FontB24_CharInfo[ 30] /* address of first character */
  ,&GUI_FontB24_Prop32 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_FontB24_Prop30 = {
   0x8BBE /* first character */
  ,0x8BBE /* last character  */
  ,&GUI_FontB24_CharInfo[ 29] /* address of first character */
  ,&GUI_FontB24_Prop31 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_FontB24_Prop29 = {
   0x8BA4 /* first character */
  ,0x8BA4 /* last character  */
  ,&GUI_FontB24_CharInfo[ 28] /* address of first character */
  ,&GUI_FontB24_Prop30 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_FontB24_Prop28 = {
   0x8865 /* first character */
  ,0x8865 /* last character  */
  ,&GUI_FontB24_CharInfo[ 27] /* address of first character */
  ,&GUI_FontB24_Prop29 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_FontB24_Prop27 = {
   0x7F6E /* first character */
  ,0x7F6E /* last character  */
  ,&GUI_FontB24_CharInfo[ 26] /* address of first character */
  ,&GUI_FontB24_Prop28 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_FontB24_Prop26 = {
   0x79EF /* first character */
  ,0x79EF /* last character  */
  ,&GUI_FontB24_CharInfo[ 25] /* address of first character */
  ,&GUI_FontB24_Prop27 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_FontB24_Prop25 = {
   0x786E /* first character */
  ,0x786E /* last character  */
  ,&GUI_FontB24_CharInfo[ 24] /* address of first character */
  ,&GUI_FontB24_Prop26 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_FontB24_Prop24 = {
   0x72B6 /* first character */
  ,0x72B6 /* last character  */
  ,&GUI_FontB24_CharInfo[ 23] /* address of first character */
  ,&GUI_FontB24_Prop25 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_FontB24_Prop23 = {
   0x70ED /* first character */
  ,0x70ED /* last character  */
  ,&GUI_FontB24_CharInfo[ 22] /* address of first character */
  ,&GUI_FontB24_Prop24 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_FontB24_Prop22 = {
   0x6E29 /* first character */
  ,0x6E29 /* last character  */
  ,&GUI_FontB24_CharInfo[ 21] /* address of first character */
  ,&GUI_FontB24_Prop23 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_FontB24_Prop21 = {
   0x6D88 /* first character */
  ,0x6D88 /* last character  */
  ,&GUI_FontB24_CharInfo[ 20] /* address of first character */
  ,&GUI_FontB24_Prop22 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_FontB24_Prop20 = {
   0x6D41 /* first character */
  ,0x6D41 /* last character  */
  ,&GUI_FontB24_CharInfo[ 19] /* address of first character */
  ,&GUI_FontB24_Prop21 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_FontB24_Prop19 = {
   0x6C34 /* first character */
  ,0x6C34 /* last character  */
  ,&GUI_FontB24_CharInfo[ 18] /* address of first character */
  ,&GUI_FontB24_Prop20 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_FontB24_Prop18 = {
   0x6B62 /* first character */
  ,0x6B62 /* last character  */
  ,&GUI_FontB24_CharInfo[ 17] /* address of first character */
  ,&GUI_FontB24_Prop19 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_FontB24_Prop17 = {
   0x624B /* first character */
  ,0x624B /* last character  */
  ,&GUI_FontB24_CharInfo[ 16] /* address of first character */
  ,&GUI_FontB24_Prop18 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_FontB24_Prop16 = {
   0x606F /* first character */
  ,0x606F /* last character  */
  ,&GUI_FontB24_CharInfo[ 15] /* address of first character */
  ,&GUI_FontB24_Prop17 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_FontB24_Prop15 = {
   0x6001 /* first character */
  ,0x6001 /* last character  */
  ,&GUI_FontB24_CharInfo[ 14] /* address of first character */
  ,&GUI_FontB24_Prop16 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_FontB24_Prop14 = {
   0x5F00 /* first character */
  ,0x5F00 /* last character  */
  ,&GUI_FontB24_CharInfo[ 13] /* address of first character */
  ,&GUI_FontB24_Prop15 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_FontB24_Prop13 = {
   0x5EA6 /* first character */
  ,0x5EA6 /* last character  */
  ,&GUI_FontB24_CharInfo[ 12] /* address of first character */
  ,&GUI_FontB24_Prop14 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_FontB24_Prop12 = {
   0x59CB /* first character */
  ,0x59CB /* last character  */
  ,&GUI_FontB24_CharInfo[ 11] /* address of first character */
  ,&GUI_FontB24_Prop13 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_FontB24_Prop11 = {
   0x56DE /* first character */
  ,0x56DE /* last character  */
  ,&GUI_FontB24_CharInfo[ 10] /* address of first character */
  ,&GUI_FontB24_Prop12 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_FontB24_Prop10 = {
   0x53D6 /* first character */
  ,0x53D6 /* last character  */
  ,&GUI_FontB24_CharInfo[  9] /* address of first character */
  ,&GUI_FontB24_Prop11 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_FontB24_Prop9 = {
   0x53CC /* first character */
  ,0x53CC /* last character  */
  ,&GUI_FontB24_CharInfo[  8] /* address of first character */
  ,&GUI_FontB24_Prop10 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_FontB24_Prop8 = {
   0x5355 /* first character */
  ,0x5355 /* last character  */
  ,&GUI_FontB24_CharInfo[  7] /* address of first character */
  ,&GUI_FontB24_Prop9 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_FontB24_Prop7 = {
   0x52A8 /* first character */
  ,0x52A8 /* last character  */
  ,&GUI_FontB24_CharInfo[  6] /* address of first character */
  ,&GUI_FontB24_Prop8 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_FontB24_Prop6 = {
   0x52A0 /* first character */
  ,0x52A0 /* last character  */
  ,&GUI_FontB24_CharInfo[  5] /* address of first character */
  ,&GUI_FontB24_Prop7 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_FontB24_Prop5 = {
   0x51FB /* first character */
  ,0x51FB /* last character  */
  ,&GUI_FontB24_CharInfo[  4] /* address of first character */
  ,&GUI_FontB24_Prop6 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_FontB24_Prop4 = {
   0x505C /* first character */
  ,0x505C /* last character  */
  ,&GUI_FontB24_CharInfo[  3] /* address of first character */
  ,&GUI_FontB24_Prop5 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_FontB24_Prop3 = {
   0x4FE1 /* first character */
  ,0x4FE1 /* last character  */
  ,&GUI_FontB24_CharInfo[  2] /* address of first character */
  ,&GUI_FontB24_Prop4 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_FontB24_Prop2 = {
   0x4FDD /* first character */
  ,0x4FDD /* last character  */
  ,&GUI_FontB24_CharInfo[  1] /* address of first character */
  ,&GUI_FontB24_Prop3 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_FontB24_Prop1 = {
   0x4F53 /* first character */
  ,0x4F53 /* last character  */
  ,&GUI_FontB24_CharInfo[  0] /* address of first character */
  ,&GUI_FontB24_Prop2 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT GUI_FontB24 = {
   GUI_FONTTYPE_PROP /* type of font    */
  ,24 /* height of font  */
  ,24 /* space of font y */
  ,1 /* magnification x */
  ,1 /* magnification y */
  ,{&GUI_FontB24_Prop1}
  ,18 /* Baseline */
  ,8 /* Height of lowercase characters */
  ,13 /* Height of capital characters */
};

