/*********************************************************************
*                SEGGER Microcontroller GmbH & Co. KG                *
*        Solutions for real time microcontroller applications        *
*                           www.segger.com                           *
**********************************************************************
*                                                                    *
* C-file generated by                                                *
*                                                                    *
*        emWin Font Converter (ST) version 5.40                      *
*        Compiled Mar 17 2017, 15:34:36                              *
*                                                                    *
*        (c) 1998 - 2017 Segger Microcontroller GmbH & Co. KG        *
*                                                                    *
**********************************************************************
*                                                                    *
* Source file: B24.c                                                 *
* Font:        »ªÎÄËÎÌå                                              *
* Height:      24                                                    *
*                                                                    *
**********************************************************************
*                                                                    *
* Initial font height:  24                                           *
* Range disabled:       0000 - FFFF                                  *
* Read pattern file: C:\Users\IT\Desktop\Font\Heater_unicode.txt     *
*                                                                    *
**********************************************************************
*/

#include "GUI.h"

#ifndef GUI_CONST_STORAGE
  #define GUI_CONST_STORAGE const
#endif

/* The following line needs to be included in any file selecting the
   font.
*/
extern GUI_CONST_STORAGE GUI_FONT GUI_FontB24;

/* Start of unicode area <CJK Unified Ideographs> */
GUI_CONST_STORAGE unsigned char acGUI_FontB24_4E2D[ 60] = { /* code 4E2D */
  ________,XX______,________,
  ________,XX______,________,
  ________,XX______,________,
  ________,XX______,________,
  XX______,XX______,XX______,
  XXXXXXXX,XXXXXXXX,XX______,
  XX______,XX______,XX______,
  XX______,XX______,XX______,
  XX______,XX______,XX______,
  XX______,XX______,XX______,
  XX______,XX______,XX______,
  XXXXXXXX,XXXXXXXX,XX______,
  XX______,XX______,XX______,
  XX______,XX______,________,
  ________,XX______,________,
  ________,XX______,________,
  ________,XX______,________,
  ________,XX______,________,
  ________,XX______,________,
  ________,XX______,________};

GUI_CONST_STORAGE unsigned char acGUI_FontB24_4F53[ 60] = { /* code 4F53 */
  ________,___XX___,________,
  ____XXX_,___XX___,________,
  ____XX__,___XX___,________,
  ____XX__,___XX___,________,
  ___XX___,___XX___,XXX_____,
  ___XXXXX,XXXXXXXX,XXX_____,
  ___XXX__,__XXXXX_,________,
  __XXX___,__XXXXX_,________,
  _XXXX___,_XXXXXX_,________,
  _XXXX___,XX_XXXX_,________,
  XX_XX___,XX_XX_XX,________,
  ___XX__X,X__XX_XX,________,
  ___XX_XX,___XX_XX,X_______,
  ___XXXXX,XXXXXXXX,XX______,
  ___XXX__,___XX___,XXX_____,
  ___XX___,___XX___,_XXX____,
  ___XX___,___XX___,________,
  ___XX___,___XX___,________,
  ___XX___,___XX___,________,
  ________,________,________};

GUI_CONST_STORAGE unsigned char acGUI_FontB24_4FE1[ 57] = { /* code 4FE1 */
  _____XX_,___XX___,________,
  ____XXX_,____XX__,________,
  ____XX__,____XX__,________,
  ____XX__,________,_XXX____,
  ___XX_XX,XXXXXXXX,XXXX____,
  ___XX___,________,________,
  __XXX___,________,XX______,
  __XXX__X,XXXXXXXX,XXX_____,
  _XXXX___,________,XX______,
  _XXXX__X,XXXXXXXX,XXX_____,
  XX_XX___,________,________,
  ___XX___,XX______,XX______,
  ___XX___,XXXXXXXX,XXX_____,
  ___XX___,XX______,XX______,
  ___XX___,XX______,XX______,
  ___XX___,XX______,XX______,
  ___XX___,XXXXXXXX,XX______,
  ___XX___,XX______,XX______,
  ___XX___,XX______,XX______};

GUI_CONST_STORAGE unsigned char acGUI_FontB24_505C[ 60] = { /* code 505C */
  ____XXX_,__XXX___,________,
  ____XX__,___XXX__,________,
  ____XX__,___XX___,_XX_____,
  ___XXXXX,XXXXXXXX,XXXX____,
  ___XX___,XX_____X,X_______,
  ___XX___,XXXXXXXX,X_______,
  __XXX___,XX_____X,X_______,
  _XXXX___,XXXXXXXX,X_______,
  _XXXX_XX,XX_____X,X_XX____,
  XX_XX_XX,XXXXXXXX,XXXXX___,
  ___XX_XX,________,_XX_____,
  ___XXXXX,________,XX______,
  ___XX__X,XXXXXXXX,XXX_____,
  ___XX___,____XX__,________,
  ___XX___,____XX__,________,
  ___XX___,____XX__,________,
  ___XX___,____XX__,________,
  ___XX___,XXX_XX__,________,
  ___XX___,__XXXX__,________,
  ________,___XX___,________};

GUI_CONST_STORAGE unsigned char acGUI_FontB24_5173[ 57] = { /* code 5173 */
  ____XX__,_____XX_,________,
  _____XX_,_____XX_,________,
  ______XX,X___XX__,________,
  _______X,X__XX___,________,
  ________,__XX___X,XX______,
  __XXXXXX,XXXXXXXX,XX______,
  ________,_XX_____,________,
  ________,_XX_____,________,
  ________,_XX_____,XXX_____,
  XXXXXXXX,XXXXXXXX,XXX_____,
  ________,XXXX____,________,
  ________,XXXX____,________,
  ________,XX_XX___,________,
  _______X,X__XX___,________,
  _______X,X___XX__,________,
  ______XX,_____XX_,________,
  ____XXX_,______XX,X_______,
  ___XX___,_______X,XXXX____,
  _XXX____,________,XX______};

GUI_CONST_STORAGE unsigned char acGUI_FontB24_51FA[ 57] = { /* code 51FA */
  ________,XXX_____,________,
  ________,XX______,________,
  __XX____,XX____XX,________,
  __XX____,XX____XX,________,
  __XX____,XX____XX,________,
  __XX____,XX____XX,________,
  __XX____,XX____XX,________,
  __XX____,XX____XX,________,
  _XXXXXXX,XXXXXXXX,________,
  __XX____,XX____XX,________,
  ________,XX______,________,
  _XXX____,XX_____X,X_______,
  _XX_____,XX_____X,X_______,
  _XX_____,XX_____X,X_______,
  _XX_____,XX_____X,X_______,
  _XX_____,XX_____X,X_______,
  _XX_____,XX_____X,X_______,
  XXXXXXXX,XXXXXXXX,X_______,
  _XX_____,_______X,X_______};

GUI_CONST_STORAGE unsigned char acGUI_FontB24_51FB[ 57] = { /* code 51FB */
  ________,_XX_____,________,
  ________,_XX_____,________,
  ________,_XX_____,________,
  ________,_XX____X,X_______,
  __XXXXXX,XXXXXXXX,XX______,
  ________,_XX_____,________,
  ________,_XX_____,________,
  ________,_XX_____,________,
  ________,_XX_____,_XXX____,
  XXXXXXXX,XXXXXXXX,XXXX____,
  ________,_XX_____,________,
  ___XXX__,_XX____X,XX______,
  ___XX___,_XX____X,X_______,
  ___XX___,_XX____X,X_______,
  ___XX___,_XX____X,X_______,
  ___XX___,_XX____X,X_______,
  ___XX___,_XX____X,X_______,
  __XXXXXX,XXXXXXXX,X_______,
  ___XX___,_______X,X_______};

GUI_CONST_STORAGE unsigned char acGUI_FontB24_52A0[ 57] = { /* code 52A0 */
  ____XX__,________,________,
  ____XX__,________,________,
  ____XX__,________,________,
  ____XX__,___XX___,_XX_____,
  ____XX__,XX_XXXXX,XXXX____,
  _XXXXXXX,XXXXX___,_XX_____,
  ____XX__,XX_XX___,_XX_____,
  ____XX__,XX_XX___,_XX_____,
  ____XX__,XX_XX___,_XX_____,
  ___XX___,XX_XX___,_XX_____,
  ___XX___,XX_XX___,_XX_____,
  ___XX___,XX_XX___,_XX_____,
  ___XX___,XX_XX___,_XX_____,
  ___XX___,XX_XX___,_XX_____,
  __XX___X,XX_XX___,_XX_____,
  __XX___X,X__XXXXX,XXX_____,
  __XX___X,X__XX___,_XX_____,
  _XX_XXXX,X__XX___,_XX_____,
  XX____XX,___XX___,________};

GUI_CONST_STORAGE unsigned char acGUI_FontB24_52A8[ 60] = { /* code 52A8 */
  ________,____XXX_,________,
  ________,____XX__,________,
  ________,XX__XX__,________,
  _XXXXXXX,XX__XX__,________,
  ________,____XX__,_XX_____,
  ________,_XXXXXXX,XXXX____,
  ________,XX__XX__,_XX_____,
  XXXXXXXX,XXX_XX__,_XX_____,
  ____XXX_,____XX__,_XX_____,
  ____XX__,____XX__,_XX_____,
  ___XX_XX,____XX__,_XX_____,
  ___XX__X,X__XX___,_XX_____,
  __XX___X,X__XX___,_XX_____,
  __XX____,XX_XX___,_XX_____,
  _XXXXXXX,XXXX____,_XX_____,
  _XXX____,XXXX____,XXX_____,
  ________,_XX_____,XX______,
  _______X,XX___XXX,XX______,
  ______XX,_______X,X_______,
  _____XX_,________,________};

GUI_CONST_STORAGE unsigned char acGUI_FontB24_5347[ 57] = { /* code 5347 */
  ________,_____XX_,________,
  ________,__XX_XX_,________,
  ______XX,XXX__XX_,________,
  _XXXXXXX,_____XX_,________,
  ______XX,_____XX_,________,
  ______XX,_____XX_,________,
  ______XX,_____XX_,________,
  ______XX,_____XX_,_XX_____,
  XXXXXXXX,XXXXXXXX,XXXX____,
  ______XX,_____XX_,________,
  ______XX,_____XX_,________,
  ______XX,_____XX_,________,
  _____XX_,_____XX_,________,
  _____XX_,_____XX_,________,
  _____XX_,_____XX_,________,
  ____XX__,_____XX_,________,
  ___XXX__,_____XX_,________,
  __XX____,_____XX_,________,
  _XX_____,_____XX_,________};

GUI_CONST_STORAGE unsigned char acGUI_FontB24_5355[ 60] = { /* code 5355 */
  _____XX_,_____XXX,________,
  ______XX,____XX__,________,
  ___XX_XX,X__XX___,XX______,
  ___XXXXX,XXXXXXXX,XXX_____,
  ___XX___,_XX_____,XX______,
  ___XX___,_XX_____,XX______,
  ___XX___,_XX_____,XX______,
  ___XXXXX,XXXXXXXX,XX______,
  ___XX___,_XX_____,XX______,
  ___XX___,_XX_____,XX______,
  ___XXXXX,XXXXXXXX,XX______,
  ___XX___,_XX_____,XX______,
  ________,_XX_____,________,
  ________,_XX_____,_XX_____,
  XXXXXXXX,XXXXXXXX,XXXX____,
  ________,_XX_____,________,
  ________,_XX_____,________,
  ________,_XX_____,________,
  ________,_XX_____,________,
  ________,_XX_____,________};

GUI_CONST_STORAGE unsigned char acGUI_FontB24_53CC[ 54] = { /* code 53CC */
  _______X,X_______,XX______,
  XXXXXXXX,XXXXXXXX,XXX_____,
  _______X,X_XX____,XX______,
  _______X,X_XX____,XX______,
  _XX___XX,__XX___X,X_______,
  __XX__XX,__XX___X,X_______,
  ___XX_XX,__XXX__X,X_______,
  ____XXXX,___XX__X,X_______,
  ____XXX_,___XX_XX,________,
  _____XX_,___XX_XX,________,
  ____XXXX,___XXXX_,________,
  ____XXXX,____XX__,________,
  ___XX_XX,X___XXX_,________,
  __XX___X,X__XXXXX,________,
  __XX___X,XXXX__XX,X_______,
  _XX_____,XX_____X,XXX_____,
  XX____XX,X_______,XX______,
  ____XXX_,________,________};

GUI_CONST_STORAGE unsigned char acGUI_FontB24_53D6[ 57] = { /* code 53D6 */
  ________,___XX___,________,
  _XXXXXXX,XXXXX___,________,
  ___XX___,XX______,XX______,
  ___XX___,XXXXXXXX,XXX_____,
  ___XX___,XX_XX___,_XX_____,
  ___XXXXX,XX_XX___,XX______,
  ___XX___,XX_XX___,XX______,
  ___XX___,XX_XXX__,XX______,
  ___XX___,XX__XX__,XX______,
  ___XXXXX,XX__XX_X,X_______,
  ___XX___,XX__XXXX,X_______,
  ___XX___,XX___XXX,X_______,
  ___XX___,XXXXXXXX,________,
  ___XX_XX,XX___XXX,________,
  __XXXXX_,XX___XXX,X_______,
  _XX_____,XX__XX_X,XX______,
  ________,XX_XX___,XXXX____,
  ________,XXXX____,________,
  ________,XXX_____,________};

GUI_CONST_STORAGE unsigned char acGUI_FontB24_53EF[ 54] = { /* code 53EF */
  ________,________,_XX_____,
  XXXXXXXX,XXXXXXXX,XXXX____,
  ________,______XX,________,
  ________,______XX,________,
  ___XX___,_XX___XX,________,
  ___XXXXX,XXXX__XX,________,
  ___XX___,_XX___XX,________,
  ___XX___,_XX___XX,________,
  ___XX___,_XX___XX,________,
  ___XX___,_XX___XX,________,
  ___XX___,_XX___XX,________,
  ___XXXXX,XXX___XX,________,
  ___XX___,_XX___XX,________,
  ___XX___,______XX,________,
  ________,______XX,________,
  ________,______XX,________,
  ________,___XXXXX,________,
  ________,_____XX_,________};

GUI_CONST_STORAGE unsigned char acGUI_FontB24_56DE[ 57] = { /* code 56DE */
  ________,________,________,
  XX______,______XX,X_______,
  XXXXXXXX,XXXXXXXX,________,
  XX______,______XX,________,
  XX______,______XX,________,
  XX__XX__,__XX__XX,________,
  XX__XXXX,XXXXX_XX,________,
  XX__XX__,__XX__XX,________,
  XX__XX__,__XX__XX,________,
  XX__XX__,__XX__XX,________,
  XX__XX__,__XX__XX,________,
  XX__XXXX,XXXX__XX,________,
  XX__XX__,__XX__XX,________,
  XX__XX__,______XX,________,
  XX______,______XX,________,
  XXXXXXXX,XXXXXXXX,________,
  XX______,______XX,________,
  XX______,______XX,________,
  XX______,________,________};

GUI_CONST_STORAGE unsigned char acGUI_FontB24_59CB[ 57] = { /* code 59CB */
  ____XXX_,_____XX_,________,
  ____XX__,_____XX_,________,
  ____XX__,____XX__,________,
  ____XX__,____XX__,________,
  ____XX_X,X__XX__X,X_______,
  _XXXXXXX,X_XX____,XX______,
  ___XX__X,X_XX____,_XX_____,
  ___XX__X,XXXXXXXX,XXXX____,
  ___XX__X,XXXXX___,__XX____,
  ___XX__X,X_______,__XX____,
  ___XX_XX,__XX____,XX______,
  __XX__XX,__XXXXXX,XXX_____,
  __XX__XX,__XX____,XX______,
  ___XXXX_,__XX____,XX______,
  ____XXX_,__XX____,XX______,
  ____XXXX,X_XX____,XX______,
  ___XX__X,X_XXXXXX,XX______,
  __XX___X,X_XX____,XX______,
  _XX_____,__XX____,XX______};

GUI_CONST_STORAGE unsigned char acGUI_FontB24_5EA6[ 60] = { /* code 5EA6 */
  ________,__XXX___,________,
  ________,___XX___,________,
  ___XX___,________,_XXX____,
  ___XXXXX,XXXXXXXX,XXXX____,
  ___XX___,_XX___XX,________,
  ___XX___,_XX___XX,__XX____,
  ___XX_XX,XXXXXXXX,XXXXX___,
  ___XX___,_XX___XX,________,
  ___XX___,_XX___XX,________,
  ___XX___,_XXXXXXX,________,
  ___XX___,_XX___XX,________,
  ___XX_XX,XXXXXXXX,X_______,
  ___XX___,XX____XX,________,
  ___XX___,_XX__XX_,________,
  __XX____,_XX__XX_,________,
  __XX____,__XXXX__,________,
  __XX____,___XXXX_,________,
  _XX_____,_XXX_XXX,XXX_____,
  _XX___XX,XX______,XXXX____,
  ___XXXX_,________,________};

GUI_CONST_STORAGE unsigned char acGUI_FontB24_5F00[ 57] = { /* code 5F00 */
  ________,________,________,
  ________,________,XX______,
  _XXXXXXX,XXXXXXXX,XXX_____,
  ______XX,____XX__,________,
  ______XX,____XX__,________,
  ______XX,____XX__,________,
  ______XX,____XX__,________,
  ______XX,____XX__,_XX_____,
  XXXXXXXX,XXXXXXXX,XXXX____,
  ______XX,____XX__,________,
  ______XX,____XX__,________,
  ______XX,____XX__,________,
  ______XX,____XX__,________,
  _____XX_,____XX__,________,
  _____XX_,____XX__,________,
  ____XX__,____XX__,________,
  ___XX___,____XX__,________,
  __XX____,____XX__,________,
  _XX_____,____XX__,________};

GUI_CONST_STORAGE unsigned char acGUI_FontB24_5F85[ 60] = { /* code 5F85 */
  ________,____XXX_,________,
  _____XXX,____XX__,________,
  _____XX_,____XX__,_XX_____,
  ____XX__,XXXXXXXX,XXXX____,
  ___XX___,____XX__,________,
  _XXX_XXX,____XX__,________,
  _____XX_,____XX__,__XX____,
  ____XXXX,XXXXXXXX,XXXXX___,
  ____XX__,_______X,X_______,
  ___XXX__,_______X,X_______,
  __XXXX__,_______X,X_XX____,
  _XX_XX__,XXXXXXXX,XXXXX___,
  XX__XX__,_______X,X_______,
  ____XX__,__XX___X,X_______,
  ____XX__,__XXX__X,X_______,
  ____XX__,___XX__X,X_______,
  ____XX__,_______X,X_______,
  ____XX__,_______X,X_______,
  ____XX__,_____XXX,X_______,
  ________,______XX,________};

GUI_CONST_STORAGE unsigned char acGUI_FontB24_6001[ 57] = { /* code 6001 */
  ________,_XX_____,________,
  ________,_XX_____,________,
  ________,_XX_____,________,
  ________,XX______,XXX_____,
  XXXXXXXX,XXXXXXXX,XXX_____,
  ________,XX_XX___,________,
  ________,XX_XX___,________,
  _______X,X___XX__,________,
  ______XX,X___XX__,________,
  ______XX,XXX__XX_,________,
  ____XXX_,_XXX__XX,X_______,
  ___XX___,_______X,XXXX____,
  _XXX__XX,_XX_____,_XX_____,
  XX_XX_XX,__XX____,XX______,
  ___XX_XX,__XX__XX,XXX_____,
  __XX__XX,______XX,_XXX____,
  _XXX__XX,______XX,__XX____,
  _XX___XX,______XX,X_______,
  ______XX,XXXXXXXX,________};

GUI_CONST_STORAGE unsigned char acGUI_FontB24_606F[ 57] = { /* code 606F */
  ________,XXX_____,________,
  ________,XX______,________,
  ___XX__X,X______X,X_______,
  ___XXXXX,XXXXXXXX,XX______,
  ___XX___,_______X,X_______,
  ___XXXXX,XXXXXXXX,X_______,
  ___XX___,_______X,X_______,
  ___XX___,_______X,X_______,
  ___XXXXX,XXXXXXXX,X_______,
  ___XX___,_______X,X_______,
  ___XX___,_______X,X_______,
  ___XXXXX,XXXXXXXX,X_______,
  ___XX___,_______X,X_______,
  _____XX_,_XX_____,________,
  _____XX_,__XX____,XX______,
  __XX_XX_,__XX_XX_,_XX_____,
  __XX_XX_,_____XX_,__XX____,
  XXX__XX_,_____XXX,__XX____,
  _____XXX,XXXXXXX_,________};

GUI_CONST_STORAGE unsigned char acGUI_FontB24_624B[ 54] = { /* code 624B */
  ________,__XXXXXX,X_______,
  _XXXXXXX,XXX_____,________,
  ________,_XX_____,________,
  ________,_XX_____,________,
  ________,_XX____X,X_______,
  __XXXXXX,XXXXXXXX,XX______,
  ________,_XX_____,________,
  ________,_XX_____,________,
  ________,_XX_____,_XX_____,
  XXXXXXXX,XXXXXXXX,XXXX____,
  ________,_XX_____,________,
  ________,_XX_____,________,
  ________,_XX_____,________,
  ________,_XX_____,________,
  ________,_XX_____,________,
  ________,_XX_____,________,
  _______X,XXX_____,________,
  ________,XXX_____,________};

GUI_CONST_STORAGE unsigned char acGUI_FontB24_6309[ 60] = { /* code 6309 */
  ____XX__,____XX__,________,
  ____XX__,_____XX_,________,
  ____XX__,_____XX_,__XX____,
  ____XX__,_XXXXXXX,XXXXX___,
  ____XXXX,_XX_____,__XX____,
  _XXXXXXX,XX__XX__,_XX_____,
  ____XX__,XX__XX__,________,
  ____XX__,___XX___,________,
  ____XXXX,X__XX___,__XXX___,
  ____XXXX,XXXXXXXX,XXXXX___,
  ___XXX__,___XX___,XX______,
  _XXXXX__,__XX____,XX______,
  _XX_XX__,__XX___X,X_______,
  ____XX__,_XX____X,X_______,
  ____XX__,__XXXX_X,X_______,
  ____XX__,_____XXX,________,
  ____XX__,_____XXX,XX______,
  ____XX__,___XXX__,_XXX____,
  __XXXX__,XXXX____,__XX____,
  ___XX__X,X_______,________};

GUI_CONST_STORAGE unsigned char acGUI_FontB24_6587[ 60] = { /* code 6587 */
  ________,XX______,________,
  ________,_XX_____,________,
  ________,_XXX____,________,
  ________,__XX____,_XX_____,
  XXXXXXXX,XXXXXXXX,XXXX____,
  ______XX,_____XX_,________,
  ______XX,____XX__,________,
  ______XX,____XX__,________,
  ______XX,____XX__,________,
  _______X,X___XX__,________,
  _______X,X__XX___,________,
  ________,XX_XX___,________,
  ________,XXXX____,________,
  ________,_XXX____,________,
  ________,XXXXX___,________,
  _______X,XX_XXX__,________,
  ______XX,_____XXX,________,
  ____XXX_,______XX,XXX_____,
  __XXX___,________,XX______,
  _XX_____,________,________};

GUI_CONST_STORAGE unsigned char acGUI_FontB24_65F6[ 57] = { /* code 65F6 */
  ________,______XX,________,
  XX___XX_,______XX,________,
  XXXXXXXX,______XX,________,
  XX___XX_,______XX,________,
  XX___XX_,______XX,_XX_____,
  XX___XXX,XXXXXXXX,XXX_____,
  XX___XX_,______XX,________,
  XX___XX_,______XX,________,
  XXXXXXX_,XX____XX,________,
  XX___XX_,_XX___XX,________,
  XX___XX_,__XX__XX,________,
  XX___XX_,__XX__XX,________,
  XX___XX_,______XX,________,
  XX___XX_,______XX,________,
  XXXXXXX_,______XX,________,
  XX___XX_,______XX,________,
  XX______,______XX,________,
  ________,__XXX_XX,________,
  ________,____XXXX,________};

GUI_CONST_STORAGE unsigned char acGUI_FontB24_673A[ 57] = { /* code 673A */
  ____XX__,________,________,
  ____XX__,__XX___X,X_______,
  ____XX__,__XXXXXX,X_______,
  ____XX_X,X_XX___X,X_______,
  _XXXXXXX,XXXX___X,X_______,
  ____XX__,__XX___X,X_______,
  ___XXX__,__XX___X,X_______,
  ___XXX__,__XX___X,X_______,
  ___XXXXX,__XX___X,X_______,
  __XXXX_X,X_XX___X,X_______,
  __XXXX_X,X_XX___X,X_______,
  _XX_XX__,__XX___X,X_______,
  _XX_XX__,__XX___X,X_______,
  XX__XX__,__XX___X,X_XX____,
  ____XX__,_XX____X,X_XX____,
  ____XX__,_XX____X,X_XX____,
  ____XX__,XX_____X,X_XXX___,
  ____XX__,XX_____X,XXXX____,
  ____XX_X,X_______,________};

GUI_CONST_STORAGE unsigned char acGUI_FontB24_6B62[ 54] = { /* code 6B62 */
  ________,__XX____,________,
  ________,__XX____,________,
  ________,__XX____,________,
  ________,__XX____,________,
  ____XX__,__XX____,________,
  ____XX__,__XX____,________,
  ____XX__,__XX____,________,
  ____XX__,__XX___X,XX______,
  ____XX__,__XXXXXX,XX______,
  ____XX__,__XX____,________,
  ____XX__,__XX____,________,
  ____XX__,__XX____,________,
  ____XX__,__XX____,________,
  ____XX__,__XX____,________,
  ____XX__,__XX____,________,
  ____XX__,__XX____,________,
  ____XX__,__XX____,_XX_____,
  XXXXXXXX,XXXXXXXX,XXXX____};

GUI_CONST_STORAGE unsigned char acGUI_FontB24_6C34[ 60] = { /* code 6C34 */
  ________,_XX_____,________,
  ________,_XX_____,________,
  ________,_XX_____,________,
  ________,_XX_____,________,
  ________,_XXX___X,XX______,
  ______XX,_XXX__XX,X_______,
  XXXXXXXX,XXXX_XXX,________,
  ______XX,_XXXXX__,________,
  _____XXX,_XXXX___,________,
  _____XX_,_XX_XX__,________,
  _____XX_,_XX_XX__,________,
  ____XX__,_XX__XX_,________,
  ____XX__,_XX__XX_,________,
  ___XX___,_XX___XX,________,
  ___XX___,_XX____X,X_______,
  __XX____,_XX____X,XXX_____,
  _XX_____,_XX_____,XXX_____,
  XX____XX,_XX_____,________,
  _______X,XXX_____,________,
  ________,________,________};

GUI_CONST_STORAGE unsigned char acGUI_FontB24_6D41[ 60] = { /* code 6D41 */
  ________,___XX___,________,
  ___XX___,____XXX_,________,
  ____XX__,____XX__,__XX____,
  ____XXXX,XXXXXXXX,XXXXX___,
  ______XX,___XXXXX,________,
  ______XX,__XXX__X,XX______,
  _XXX_XX_,_XX_____,XXX_____,
  __XXXXXX,XXXXXXXX,XXXX____,
  ___XXXX_,________,_XX_____,
  ____XX__,________,________,
  ____XX__,XXX_XXXX,XX______,
  ____XX__,XX__XX_X,X_______,
  ___XX___,XX__XX_X,X_______,
  _XXXX___,XX__XX_X,X_______,
  ___XX___,XX__XX_X,X_XX____,
  ___XX___,XX__XX_X,X_XX____,
  ___XX___,XX__XX_X,X_XX____,
  ___XX__X,X___XX_X,X_XXX___,
  ___XX_XX,____XX_X,XXXXX___,
  _____XX_,________,________};

GUI_CONST_STORAGE unsigned char acGUI_FontB24_6D88[ 60] = { /* code 6D88 */
  ________,____XXX_,________,
  ___XX__X,X___XX__,_XX_____,
  ____XX__,XXX_XX__,XX______,
  ____XX__,_XXXXX_X,X_______,
  ______XX,__XXXX_X,X_______,
  XX____XX,XX__XX__,_XX_____,
  _XXX_XX_,XXXXXXXX,XXXX____,
  __XX_XX_,XX______,_XX_____,
  _____XX_,XX______,_XX_____,
  ____XX__,XXXXXXXX,XXX_____,
  ____XX__,XX______,_XX_____,
  ____XX__,XX______,_XX_____,
  ___XX___,XX______,_XX_____,
  _XXXX___,XXXXXXXX,XXX_____,
  ___XX___,XX______,_XX_____,
  ___XX___,XX______,_XX_____,
  ___XX___,XX______,_XX_____,
  ___XX___,XX____XX,_XX_____,
  ___XX___,XX_____X,XXX_____,
  ________,________,XX______};

GUI_CONST_STORAGE unsigned char acGUI_FontB24_6E29[ 57] = { /* code 6E29 */
  ________,________,________,
  __XX___X,XXXXXXXX,XX______,
  ___XX__X,X______X,X_______,
  ___XXXXX,X______X,X_______,
  _____XXX,XXXXXXXX,X_______,
  _____XXX,X______X,X_______,
  _XXXXX_X,X______X,X_______,
  __XXXX_X,X______X,X_______,
  ____XX_X,XXXXXXXX,X_______,
  ___XX__X,X______X,XX______,
  ___XX_XX,XXXXXXXX,XX______,
  ___XX_XX,_XX_XX__,XX______,
  __XX__XX,_XX_XX__,XX______,
  _XXX__XX,_XX_XX__,XX______,
  __XX__XX,_XX_XX__,XX______,
  __XX__XX,_XX_XX__,XX______,
  __XX__XX,_XX_XX__,XXXX____,
  __XXXXXX,XXXXXXXX,XXXX____,
  __XX____,________,________};

GUI_CONST_STORAGE unsigned char acGUI_FontB24_70ED[ 57] = { /* code 70ED */
  ____XX__,___XX___,________,
  ____XX__,___XX___,________,
  ____XX__,___XX___,________,
  ____XX_X,X__XX_XX,________,
  XXXXXXXX,XXXXXXXX,X_______,
  ____XX__,___XX_XX,________,
  ____XX_X,X__XX_XX,________,
  ____XXXX,XXXXX_XX,________,
  ___XXX__,__XX__XX,________,
  XXXXXX__,__XXX_XX,_XX_____,
  ____XX__,__XXXXXX,_XX_____,
  ____XX__,_XX_XX_X,XXX_____,
  _XXXXX__,XX_____X,XXX_____,
  ___XXX_X,X_______,XXX_____,
  ________,________,________,
  ___XX___,___XX__X,X_______,
  ___XX_XX,___XX___,XX______,
  __XXX__X,X___XX__,XXX_____,
  XXXX___X,X_______,_XX_____};

GUI_CONST_STORAGE unsigned char acGUI_FontB24_72B6[ 57] = { /* code 72B6 */
  _____XX_,___XXX__,________,
  _____XX_,___XX_XX,________,
  _____XX_,___XX__X,X_______,
  XX___XX_,___XX___,XX______,
  _XX__XX_,___XX___,XX______,
  __XX_XX_,___XX___,_XX_____,
  __XX_XXX,XXXXXXXX,XXXX____,
  __XX_XX_,___XXX__,________,
  _____XX_,___XXX__,________,
  ____XXX_,___XXXX_,________,
  ___XXXX_,__XX_XX_,________,
  __XX_XX_,__XX_XX_,________,
  _XX__XX_,__XX_XX_,________,
  XXX__XX_,__XX__XX,________,
  _____XX_,_XX___XX,X_______,
  _____XX_,_XX____X,X_______,
  _____XX_,XX______,XXX_____,
  _____XXX,X_______,XXX_____,
  _____XXX,________,________};

GUI_CONST_STORAGE unsigned char acGUI_FontB24_786E[ 60] = { /* code 786E */
  ________,___XXX__,________,
  ________,___XX___,________,
  _______X,X_XXX__X,X_______,
  _XXXXXXX,XXXXXXXX,XX______,
  ____XX__,_XXX__XX,________,
  ____XX__,XXX__XX_,_XX_____,
  ___XX__X,XXXXXXXX,XXXX____,
  ___XX_XX,_XX__XX_,_XX_____,
  ___XXXXX,_XX__XX_,_XX_____,
  __XXX_XX,_XXXXXXX,XXX_____,
  __XXX_XX,_XX__XX_,_XX_____,
  _XXXX_XX,_XX__XX_,_XX_____,
  XX_XX_XX,_XXXXXXX,XXX_____,
  ___XX_XX,_XX__XX_,_XX_____,
  ___XXXXX,_XX__XX_,_XX_____,
  ___XX_XX,XX___XX_,_XX_____,
  ___XX___,XX___XX_,_XX_____,
  ___XX__X,X____XXX,XXX_____,
  ______XX,________,XXX_____,
  _____XX_,________,________};

GUI_CONST_STORAGE unsigned char acGUI_FontB24_79EF[ 57] = { /* code 79EF */
  _______X,X_______,________,
  _____XXX,XXXX____,XX______,
  _XXXXX__,__XXXXXX,XX______,
  ____XX__,__XX____,XX______,
  ____XX__,__XX____,XX______,
  ____XX_X,X_XX____,XX______,
  XXXXXXXX,XXXX____,XX______,
  ____XX__,__XX____,XX______,
  ___XXXX_,__XX____,XX______,
  ___XXXXX,__XXXXXX,XX______,
  __XXXX_X,X_XX____,XX______,
  __XXXX_X,X_______,XX______,
  _XX_XX__,___XX___,________,
  _XX_XX__,__XXX__X,X_______,
  XX__XX__,__XX____,XX______,
  ____XX__,_XX_____,_XX_____,
  ____XX__,XX______,_XXX____,
  ____XX_X,X_______,__XX____,
  ____XXXX,________,________};

GUI_CONST_STORAGE unsigned char acGUI_FontB24_7EA7[ 57] = { /* code 7EA7 */
  ____XX__,________,________,
  ____XX__,________,XX______,
  ___XX___,XXXXXXXX,XX______,
  ___XX___,__XX___X,X_______,
  __XX__XX,X_XX___X,X_______,
  _XX__XXX,__XX__XX,________,
  XXXXXXX_,__XX__XX,________,
  XXX__XX_,__XXXXXX,XXX_____,
  ____XX__,__XXX___,XX______,
  ___XX___,__XXX___,XX______,
  __XX____,_XX_XX__,XX______,
  _XX_XXXX,_XX_XX_X,X_______,
  XXXXX___,_XX_XX_X,X_______,
  ________,_XX__XXX,________,
  _____XXX,XX___XXX,________,
  __XXXX_X,X____XXX,X_______,
  XXX____X,X__XXX_X,XX______,
  ______XX,__XX____,_XXXX___,
  ____XXX_,XXX_____,________};

GUI_CONST_STORAGE unsigned char acGUI_FontB24_7F6E[ 54] = { /* code 7F6E */
  ________,________,XX______,
  __XXXXXX,XXXXXXXX,XXX_____,
  __XX___X,X__XX___,XX______,
  __XX___X,X__XX___,XX______,
  __XX___X,X__XX___,XX______,
  __XXXXXX,XXXXXXXX,XX______,
  __XX____,_XX_____,XXX_____,
  XXXXXXXX,XXXXXXXX,XXXX____,
  ____XX__,XX____XX,________,
  ____XXXX,XXXXXXXX,X_______,
  ____XX__,______XX,________,
  ____XXXX,XXXXXXXX,________,
  ____XX__,______XX,________,
  ____XXXX,XXXXXXXX,________,
  ____XX__,______XX,________,
  ____XXXX,XXXXXXXX,________,
  ____XX__,______XX,_XX_____,
  XXXXXXXX,XXXXXXXX,XXXX____};

GUI_CONST_STORAGE unsigned char acGUI_FontB24_82F1[ 60] = { /* code 82F1 */
  ______XX,X___XXX_,________,
  ______XX,____XX__,_XX_____,
  _XXXXXXX,XXXXXXXX,XXXX____,
  ______XX,____XX__,________,
  ______XX,_XX_XX__,________,
  ______XX,_XX_XX__,________,
  ________,_XX___XX,________,
  ____XXXX,XXXXXXXX,________,
  ____XX__,_XX___XX,________,
  ____XX__,_XX___XX,________,
  ____XX__,_XX___XX,_XX_____,
  XXXXXXXX,XXXXXXXX,XXXX____,
  ________,XXXX____,________,
  ________,XXXX____,________,
  _______X,X__XX___,________,
  ______XX,____XX__,________,
  _____XX_,_____XX_,________,
  ___XXX__,______XX,XXX_____,
  _XXX____,_______X,XX______,
  XX______,________,________};

GUI_CONST_STORAGE unsigned char acGUI_FontB24_89C1[ 57] = { /* code 89C1 */
  ________,________,________,
  ____XXXX,XXXXXXXX,X_______,
  ____XX__,______XX,________,
  ____XX__,______XX,________,
  ____XX__,_XXX__XX,________,
  ____XX__,_XX___XX,________,
  ____XX__,_XX___XX,________,
  ____XX__,_XX___XX,________,
  ____XX__,_XX___XX,________,
  ____XX__,XXXXX_XX,________,
  ____XX__,XXXX__XX,________,
  ____XX__,XXXX__XX,________,
  ________,XXXX____,_XX_____,
  _______X,X_XX____,_XX_____,
  _______X,X_XX____,_XX_____,
  ______XX,__XX____,_XX_____,
  ____XXX_,__XX____,XXXX____,
  ___XX___,___XXXXX,XXX_____,
  _XXX____,________,________};

GUI_CONST_STORAGE unsigned char acGUI_FontB24_8BA4[ 57] = { /* code 8BA4 */
  ________,____XX__,________,
  ____XX__,____XXX_,________,
  _____XX_,____XXX_,________,
  _____XXX,____XXX_,________,
  _____XX_,____XXX_,________,
  ________,____XXX_,________,
  ____XX__,____XXX_,________,
  _XXXXXX_,____XXX_,________,
  ____XX__,____XXX_,________,
  ____XX__,___XXXX_,________,
  ____XX__,___XX_XX,________,
  ____XX__,_XXXX_XX,________,
  ____XX__,XX_XX_XX,________,
  ____XX_X,X_XX___X,X_______,
  ____XXXX,__XX___X,X_______,
  ____XXX_,_XX_____,XX______,
  ____XX__,XX______,XXX_____,
  ____XX_X,X_______,_XXXX___,
  ______XX,________,________};

GUI_CONST_STORAGE unsigned char acGUI_FontB24_8BBE[ 57] = { /* code 8BBE */
  __XX____,________,________,
  ___XX___,_XXXXXXX,X_______,
  ___XXX__,_XX___XX,________,
  ____XX__,_XX___XX,________,
  ________,_XX___XX,________,
  ________,_XX___XX,________,
  ___XX___,XX____XX,XXXX____,
  XXXXXX__,XX______,________,
  ___XX_XX,X_______,________,
  ___XX___,XXXXXXXX,X_______,
  ___XX___,_XX___XX,________,
  ___XX___,_XX___XX,________,
  ___XX___,_XX__XX_,________,
  ___XX___,__XX_XX_,________,
  ___XX_XX,___XXX__,________,
  ___XXXX_,___XXX__,________,
  ___XXX__,__XX_XXX,________,
  __XXX___,XXX____X,XXXX____,
  ______XX,X_______,________};

GUI_CONST_STORAGE unsigned char acGUI_FontB24_8FD4[ 54] = { /* code 8FD4 */
  ___XX___,_______X,XXX_____,
  ____XX__,_XXXXXXX,________,
  ____XXX_,_XXX____,________,
  _____XX_,_XX_____,________,
  ________,_XX_____,XX______,
  ________,_XXXXXXX,XXX_____,
  ____XX__,_XX_____,XX______,
  _XXXXXX_,_XX_____,XX______,
  ____XX__,_XXXX__X,X_______,
  ____XX__,_XX_XX_X,X_______,
  ____XX__,XX___XXX,________,
  ____XX__,XX___XXX,X_______,
  ____XX__,XX__XXX_,XXX_____,
  ____XX_X,X__XX___,_XX_____,
  ___XXXXX,_XXX____,_XX_____,
  __XX_XX_,________,___XX___,
  _XXX__XX,________,XXXX____,
  _______X,XXXXXXXX,XXXX____};

GUI_CONST_STORAGE unsigned char acGUI_FontB24_8FDB[ 57] = { /* code 8FDB */
  ________,______XX,________,
  _XX_____,_XXX__XX,________,
  __XX____,_XX___XX,________,
  ___XX___,_XX___XX,________,
  ___XX___,_XX___XX,_XX_____,
  ______XX,XXXXXXXX,XXXX____,
  ________,_XX___XX,________,
  ___XX___,_XX___XX,________,
  XXXXXX__,_XX___XX,__XX____,
  ___XXXXX,XXXXXXXX,XXXXX___,
  ___XX___,_XX___XX,________,
  ___XX___,_XX___XX,________,
  ___XX___,XX____XX,________,
  ___XX___,XX____XX,________,
  ___XX__X,X_____XX,________,
  ___XX_XX,______XX,________,
  __XXXXX_,________,________,
  _XX__XX_,________,__XXX___,
  XX____XX,XXXXXXXX,XXX_____};

GUI_CONST_STORAGE unsigned char acGUI_FontB24_91CF[ 57] = { /* code 91CF */
  ___XX___,_______X,X_______,
  ___XXXXX,XXXXXXXX,XX______,
  ___XX___,_______X,X_______,
  ___XXXXX,XXXXXXXX,X_______,
  ___XX___,_______X,X_______,
  ___XXXXX,XXXXXXXX,X_______,
  ___XX___,_______X,XXX_____,
  XXXXXXXX,XXXXXXXX,XXXX____,
  ___XX___,_______X,X_______,
  ___XXXXX,XXXXXXXX,XX______,
  ___XX___,_XX____X,X_______,
  ___XXXXX,XXXXXXXX,X_______,
  ___XX___,_XX____X,X_______,
  ___XXXXX,XXXXXXXX,X_______,
  ___XX___,_XX____X,X_______,
  ___XXXXX,XXXXXXXX,XX______,
  ________,_XX_____,________,
  ________,_XX_____,_XX_____,
  XXXXXXXX,XXXXXXXX,XXXX____};

GUI_CONST_STORAGE unsigned char acGUI_FontB24_957F[ 57] = { /* code 957F */
  _____XX_,________,________,
  _____XX_,______XX,________,
  _____XX_,_____XXX,________,
  _____XX_,____XX__,________,
  _____XX_,__XXX___,________,
  _____XX_,_XX_____,________,
  _____XX_,XX______,________,
  _____XX_,________,________,
  _____XX_,________,_XXX____,
  XXXXXXXX,XXXXXXXX,XXXX____,
  _____XX_,_XX_____,________,
  _____XX_,__XX____,________,
  _____XX_,__XX____,________,
  _____XX_,___XX___,________,
  _____XX_,____XX__,________,
  _____XX_,____XXX_,________,
  _____XX_,XXX__XXX,X_______,
  _____XXX,X______X,XXXXX___,
  ____XXX_,________,_XX_____};

GUI_CONST_STORAGE unsigned char acGUI_FontB24_95F4[ 60] = { /* code 95F4 */
  _XX_____,________,________,
  __XXX___,_______X,X_______,
  ___XX_XX,XXXXXXXX,X_______,
  XXX_____,_______X,X_______,
  XX______,_______X,X_______,
  XX__XX__,__XX___X,X_______,
  XX__XXXX,XXXX___X,X_______,
  XX__XX__,__XX___X,X_______,
  XX__XX__,__XX___X,X_______,
  XX__XXXX,XXXX___X,X_______,
  XX__XX__,__XX___X,X_______,
  XX__XX__,__XX___X,X_______,
  XX__XX__,__XX___X,X_______,
  XX__XX__,__XX___X,X_______,
  XX__XXXX,XXXX___X,X_______,
  XX__XX__,__XX___X,X_______,
  XX______,_______X,X_______,
  XX______,____XX_X,X_______,
  XX______,_____XXX,X_______,
  ________,________,________};

GUI_CONST_STORAGE GUI_CHARINFO_EXT GUI_FontB24_CharInfo[46] = {
   {  19,  20,   2,   2,  22, acGUI_FontB24_4E2D } /* code 4E2D */
  ,{  20,  20,   1,   2,  22, acGUI_FontB24_4F53 } /* code 4F53 */
  ,{  20,  19,   1,   2,  22, acGUI_FontB24_4FE1 } /* code 4FE1 */
  ,{  21,  20,   1,   2,  22, acGUI_FontB24_505C } /* code 505C */
  ,{  20,  19,   1,   2,  22, acGUI_FontB24_5173 } /* code 5173 */
  ,{  18,  19,   2,   2,  22, acGUI_FontB24_51FA } /* code 51FA */
  ,{  20,  19,   1,   2,  22, acGUI_FontB24_51FB } /* code 51FB */
  ,{  20,  19,   1,   2,  22, acGUI_FontB24_52A0 } /* code 52A0 */
  ,{  20,  20,   1,   2,  22, acGUI_FontB24_52A8 } /* code 52A8 */
  ,{  20,  19,   1,   2,  22, acGUI_FontB24_5347 } /* code 5347 */
  ,{  20,  20,   1,   2,  22, acGUI_FontB24_5355 } /* code 5355 */
  ,{  20,  18,   1,   3,  22, acGUI_FontB24_53CC } /* code 53CC */
  ,{  21,  19,   0,   2,  22, acGUI_FontB24_53D6 } /* code 53D6 */
  ,{  20,  18,   1,   3,  22, acGUI_FontB24_53EF } /* code 53EF */
  ,{  17,  19,   3,   2,  22, acGUI_FontB24_56DE } /* code 56DE */
  ,{  20,  19,   1,   2,  22, acGUI_FontB24_59CB } /* code 59CB */
  ,{  21,  20,   0,   2,  22, acGUI_FontB24_5EA6 } /* code 5EA6 */
  ,{  20,  19,   1,   2,  22, acGUI_FontB24_5F00 } /* code 5F00 */
  ,{  21,  20,   0,   2,  22, acGUI_FontB24_5F85 } /* code 5F85 */
  ,{  20,  19,   1,   2,  22, acGUI_FontB24_6001 } /* code 6001 */
  ,{  20,  19,   1,   2,  22, acGUI_FontB24_606F } /* code 606F */
  ,{  20,  18,   1,   3,  22, acGUI_FontB24_624B } /* code 624B */
  ,{  21,  20,   0,   2,  22, acGUI_FontB24_6309 } /* code 6309 */
  ,{  20,  20,   1,   2,  22, acGUI_FontB24_6587 } /* code 6587 */
  ,{  19,  19,   2,   2,  22, acGUI_FontB24_65F6 } /* code 65F6 */
  ,{  21,  19,   1,   2,  22, acGUI_FontB24_673A } /* code 673A */
  ,{  20,  18,   1,   2,  22, acGUI_FontB24_6B62 } /* code 6B62 */
  ,{  20,  20,   1,   2,  22, acGUI_FontB24_6C34 } /* code 6C34 */
  ,{  21,  20,   0,   2,  22, acGUI_FontB24_6D41 } /* code 6D41 */
  ,{  20,  20,   1,   2,  22, acGUI_FontB24_6D88 } /* code 6D88 */
  ,{  20,  19,   1,   2,  22, acGUI_FontB24_6E29 } /* code 6E29 */
  ,{  20,  19,   1,   2,  22, acGUI_FontB24_70ED } /* code 70ED */
  ,{  20,  19,   1,   2,  22, acGUI_FontB24_72B6 } /* code 72B6 */
  ,{  20,  20,   1,   2,  22, acGUI_FontB24_786E } /* code 786E */
  ,{  20,  19,   1,   2,  22, acGUI_FontB24_79EF } /* code 79EF */
  ,{  21,  19,   1,   2,  22, acGUI_FontB24_7EA7 } /* code 7EA7 */
  ,{  20,  18,   1,   2,  22, acGUI_FontB24_7F6E } /* code 7F6E */
  ,{  20,  20,   1,   2,  22, acGUI_FontB24_82F1 } /* code 82F1 */
  ,{  20,  19,   1,   2,  22, acGUI_FontB24_89C1 } /* code 89C1 */
  ,{  22,  19,   0,   2,  22, acGUI_FontB24_8BA4 } /* code 8BA4 */
  ,{  20,  19,   1,   2,  22, acGUI_FontB24_8BBE } /* code 8BBE */
  ,{  21,  18,   0,   3,  22, acGUI_FontB24_8FD4 } /* code 8FD4 */
  ,{  21,  19,   1,   2,  22, acGUI_FontB24_8FDB } /* code 8FDB */
  ,{  20,  19,   1,   2,  22, acGUI_FontB24_91CF } /* code 91CF */
  ,{  21,  19,   1,   2,  22, acGUI_FontB24_957F } /* code 957F */
  ,{  18,  20,   3,   2,  22, acGUI_FontB24_95F4 } /* code 95F4 */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_FontB24_Prop45 = {
   0x95F4 /* first character */
  ,0x95F4 /* last character  */
  ,&GUI_FontB24_CharInfo[ 45] /* address of first character */
  ,(GUI_CONST_STORAGE GUI_FONT_PROP_EXT *)0 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_FontB24_Prop44 = {
   0x957F /* first character */
  ,0x957F /* last character  */
  ,&GUI_FontB24_CharInfo[ 44] /* address of first character */
  ,&GUI_FontB24_Prop45 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_FontB24_Prop43 = {
   0x91CF /* first character */
  ,0x91CF /* last character  */
  ,&GUI_FontB24_CharInfo[ 43] /* address of first character */
  ,&GUI_FontB24_Prop44 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_FontB24_Prop42 = {
   0x8FDB /* first character */
  ,0x8FDB /* last character  */
  ,&GUI_FontB24_CharInfo[ 42] /* address of first character */
  ,&GUI_FontB24_Prop43 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_FontB24_Prop41 = {
   0x8FD4 /* first character */
  ,0x8FD4 /* last character  */
  ,&GUI_FontB24_CharInfo[ 41] /* address of first character */
  ,&GUI_FontB24_Prop42 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_FontB24_Prop40 = {
   0x8BBE /* first character */
  ,0x8BBE /* last character  */
  ,&GUI_FontB24_CharInfo[ 40] /* address of first character */
  ,&GUI_FontB24_Prop41 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_FontB24_Prop39 = {
   0x8BA4 /* first character */
  ,0x8BA4 /* last character  */
  ,&GUI_FontB24_CharInfo[ 39] /* address of first character */
  ,&GUI_FontB24_Prop40 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_FontB24_Prop38 = {
   0x89C1 /* first character */
  ,0x89C1 /* last character  */
  ,&GUI_FontB24_CharInfo[ 38] /* address of first character */
  ,&GUI_FontB24_Prop39 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_FontB24_Prop37 = {
   0x82F1 /* first character */
  ,0x82F1 /* last character  */
  ,&GUI_FontB24_CharInfo[ 37] /* address of first character */
  ,&GUI_FontB24_Prop38 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_FontB24_Prop36 = {
   0x7F6E /* first character */
  ,0x7F6E /* last character  */
  ,&GUI_FontB24_CharInfo[ 36] /* address of first character */
  ,&GUI_FontB24_Prop37 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_FontB24_Prop35 = {
   0x7EA7 /* first character */
  ,0x7EA7 /* last character  */
  ,&GUI_FontB24_CharInfo[ 35] /* address of first character */
  ,&GUI_FontB24_Prop36 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_FontB24_Prop34 = {
   0x79EF /* first character */
  ,0x79EF /* last character  */
  ,&GUI_FontB24_CharInfo[ 34] /* address of first character */
  ,&GUI_FontB24_Prop35 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_FontB24_Prop33 = {
   0x786E /* first character */
  ,0x786E /* last character  */
  ,&GUI_FontB24_CharInfo[ 33] /* address of first character */
  ,&GUI_FontB24_Prop34 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_FontB24_Prop32 = {
   0x72B6 /* first character */
  ,0x72B6 /* last character  */
  ,&GUI_FontB24_CharInfo[ 32] /* address of first character */
  ,&GUI_FontB24_Prop33 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_FontB24_Prop31 = {
   0x70ED /* first character */
  ,0x70ED /* last character  */
  ,&GUI_FontB24_CharInfo[ 31] /* address of first character */
  ,&GUI_FontB24_Prop32 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_FontB24_Prop30 = {
   0x6E29 /* first character */
  ,0x6E29 /* last character  */
  ,&GUI_FontB24_CharInfo[ 30] /* address of first character */
  ,&GUI_FontB24_Prop31 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_FontB24_Prop29 = {
   0x6D88 /* first character */
  ,0x6D88 /* last character  */
  ,&GUI_FontB24_CharInfo[ 29] /* address of first character */
  ,&GUI_FontB24_Prop30 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_FontB24_Prop28 = {
   0x6D41 /* first character */
  ,0x6D41 /* last character  */
  ,&GUI_FontB24_CharInfo[ 28] /* address of first character */
  ,&GUI_FontB24_Prop29 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_FontB24_Prop27 = {
   0x6C34 /* first character */
  ,0x6C34 /* last character  */
  ,&GUI_FontB24_CharInfo[ 27] /* address of first character */
  ,&GUI_FontB24_Prop28 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_FontB24_Prop26 = {
   0x6B62 /* first character */
  ,0x6B62 /* last character  */
  ,&GUI_FontB24_CharInfo[ 26] /* address of first character */
  ,&GUI_FontB24_Prop27 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_FontB24_Prop25 = {
   0x673A /* first character */
  ,0x673A /* last character  */
  ,&GUI_FontB24_CharInfo[ 25] /* address of first character */
  ,&GUI_FontB24_Prop26 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_FontB24_Prop24 = {
   0x65F6 /* first character */
  ,0x65F6 /* last character  */
  ,&GUI_FontB24_CharInfo[ 24] /* address of first character */
  ,&GUI_FontB24_Prop25 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_FontB24_Prop23 = {
   0x6587 /* first character */
  ,0x6587 /* last character  */
  ,&GUI_FontB24_CharInfo[ 23] /* address of first character */
  ,&GUI_FontB24_Prop24 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_FontB24_Prop22 = {
   0x6309 /* first character */
  ,0x6309 /* last character  */
  ,&GUI_FontB24_CharInfo[ 22] /* address of first character */
  ,&GUI_FontB24_Prop23 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_FontB24_Prop21 = {
   0x624B /* first character */
  ,0x624B /* last character  */
  ,&GUI_FontB24_CharInfo[ 21] /* address of first character */
  ,&GUI_FontB24_Prop22 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_FontB24_Prop20 = {
   0x606F /* first character */
  ,0x606F /* last character  */
  ,&GUI_FontB24_CharInfo[ 20] /* address of first character */
  ,&GUI_FontB24_Prop21 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_FontB24_Prop19 = {
   0x6001 /* first character */
  ,0x6001 /* last character  */
  ,&GUI_FontB24_CharInfo[ 19] /* address of first character */
  ,&GUI_FontB24_Prop20 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_FontB24_Prop18 = {
   0x5F85 /* first character */
  ,0x5F85 /* last character  */
  ,&GUI_FontB24_CharInfo[ 18] /* address of first character */
  ,&GUI_FontB24_Prop19 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_FontB24_Prop17 = {
   0x5F00 /* first character */
  ,0x5F00 /* last character  */
  ,&GUI_FontB24_CharInfo[ 17] /* address of first character */
  ,&GUI_FontB24_Prop18 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_FontB24_Prop16 = {
   0x5EA6 /* first character */
  ,0x5EA6 /* last character  */
  ,&GUI_FontB24_CharInfo[ 16] /* address of first character */
  ,&GUI_FontB24_Prop17 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_FontB24_Prop15 = {
   0x59CB /* first character */
  ,0x59CB /* last character  */
  ,&GUI_FontB24_CharInfo[ 15] /* address of first character */
  ,&GUI_FontB24_Prop16 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_FontB24_Prop14 = {
   0x56DE /* first character */
  ,0x56DE /* last character  */
  ,&GUI_FontB24_CharInfo[ 14] /* address of first character */
  ,&GUI_FontB24_Prop15 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_FontB24_Prop13 = {
   0x53EF /* first character */
  ,0x53EF /* last character  */
  ,&GUI_FontB24_CharInfo[ 13] /* address of first character */
  ,&GUI_FontB24_Prop14 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_FontB24_Prop12 = {
   0x53D6 /* first character */
  ,0x53D6 /* last character  */
  ,&GUI_FontB24_CharInfo[ 12] /* address of first character */
  ,&GUI_FontB24_Prop13 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_FontB24_Prop11 = {
   0x53CC /* first character */
  ,0x53CC /* last character  */
  ,&GUI_FontB24_CharInfo[ 11] /* address of first character */
  ,&GUI_FontB24_Prop12 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_FontB24_Prop10 = {
   0x5355 /* first character */
  ,0x5355 /* last character  */
  ,&GUI_FontB24_CharInfo[ 10] /* address of first character */
  ,&GUI_FontB24_Prop11 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_FontB24_Prop9 = {
   0x5347 /* first character */
  ,0x5347 /* last character  */
  ,&GUI_FontB24_CharInfo[  9] /* address of first character */
  ,&GUI_FontB24_Prop10 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_FontB24_Prop8 = {
   0x52A8 /* first character */
  ,0x52A8 /* last character  */
  ,&GUI_FontB24_CharInfo[  8] /* address of first character */
  ,&GUI_FontB24_Prop9 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_FontB24_Prop7 = {
   0x52A0 /* first character */
  ,0x52A0 /* last character  */
  ,&GUI_FontB24_CharInfo[  7] /* address of first character */
  ,&GUI_FontB24_Prop8 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_FontB24_Prop6 = {
   0x51FA /* first character */
  ,0x51FB /* last character  */
  ,&GUI_FontB24_CharInfo[  5] /* address of first character */
  ,&GUI_FontB24_Prop7 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_FontB24_Prop5 = {
   0x5173 /* first character */
  ,0x5173 /* last character  */
  ,&GUI_FontB24_CharInfo[  4] /* address of first character */
  ,&GUI_FontB24_Prop6 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_FontB24_Prop4 = {
   0x505C /* first character */
  ,0x505C /* last character  */
  ,&GUI_FontB24_CharInfo[  3] /* address of first character */
  ,&GUI_FontB24_Prop5 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_FontB24_Prop3 = {
   0x4FE1 /* first character */
  ,0x4FE1 /* last character  */
  ,&GUI_FontB24_CharInfo[  2] /* address of first character */
  ,&GUI_FontB24_Prop4 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_FontB24_Prop2 = {
   0x4F53 /* first character */
  ,0x4F53 /* last character  */
  ,&GUI_FontB24_CharInfo[  1] /* address of first character */
  ,&GUI_FontB24_Prop3 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_FontB24_Prop1 = {
   0x4E2D /* first character */
  ,0x4E2D /* last character  */
  ,&GUI_FontB24_CharInfo[  0] /* address of first character */
  ,&GUI_FontB24_Prop2 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT GUI_FontB24 = {
   GUI_FONTTYPE_PROP_EXT /* type of font    */
  ,24 /* height of font  */
  ,24 /* space of font y */
  ,1 /* magnification x */
  ,1 /* magnification y */
  ,{&GUI_FontB24_Prop1}
  ,18 /* Baseline */
  ,9 /* Height of lowercase characters */
  ,13 /* Height of capital characters */
};

